import os
photos = [
'AgACAgIAAx0EZQN7rQABAiHhZR_Uu0ACxkHgL4GUcbFtUqabvIUAAna7MRvQebBIt2R_Y3qUL98BAAMCAAN5AAMwBA',
'AgACAgIAAx0CZQN7rQABAlMLZTJbHeaHzrcg1vTcCpC-KGMny-kAAuHSMRsDXZlJTLrI-guWuYEBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiHjZR_UxdG8RkzklBIUJo9XRWgWrg4AAny7MRvQebBIJEqtzBrQ_tEBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiHkZR_UyuLvHXuUdoc00tBnEjHrVkEAAn27MRvQebBIEcVhyZD6cDoBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiHlZR_Uz-N0iU2aj9Pq57mCvdZlrKkAAm29MRsLkrFI20sGoucOt-cBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiHmZR_U1aSBrjAsr3mhsGOLlNwWYhAAAm69MRsLkrFIp59XCalYX7ABAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiHnZR_U2n_moOK4npXuA7koG5U1EZwAAm6-MRsLkrFIq3H_Rtsd1PcBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiHoZR_U31HqCh8RLzNjxOiRncTeE6cAAm2-MRsLkrFIhVKVRaOSg4UBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiHpZR_U5Oq3ycVrvdGAd-hkEuZVtHcAAm--MRsLkrFI6snJSeac_AkBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiHqZR_U6egupm0shikEcNbnMg8nF04AAnC-MRsLkrFINEiTClwxaSQBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiHrZR_U7ggbuy_uKv1VLI7Fl8f87qoAAnO-MRsLkrFIxIY8lQw9R_IBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiHsZR_U9JAKG_ars8eMH_pROgOX3OEAAiu8MRvkWhhK974w5TRGaVsBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiHtZR_U-S21O6YyGNlFDUizLN5D-kYAAiy8MRvkWhhKck3xvgABHoFCAQADAgADeAADMAQ',
'AgACAgIAAx0EZQN7rQABAiHuZR_U_owdaGaQruEYnrv42F3tLesAAi28MRvkWhhKJESwvU3cHToBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiHvZR_VA-p99_2YEHsyPRucEHeDokQAAjG8MRvkWhhKMYHtR3StDDoBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiHwZR_VCMvEcwJEWvMqmCAGhs54HDwAAjK8MRvkWhhKjZ-YtKi3008BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiHxZR_VDvqp4KQAASDG9yv5IGcisQQ8AAIzvDEb5FoYSiWtvfJJQbrKAQADAgADeQADMAQ',
'AgACAgIAAx0EZQN7rQABAiHyZR_VE8x9n0wf73t6LVqwqWIH1pUAAjS8MRvkWhhKzML8iw3LbtoBAAMCAAN5AAMwBA',
'AgACAgIAAx0CZQN7rQABAlMkZTJb162UDDj8Z-sRvKu2rsvQt3wAAuXSMRsDXZlJMOKrc0j3qwkBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiH0ZR_VHcuyv5CP0Onixo2-dFnyo-AAAkC8MRvkWhhKL4wNeXcuwyQBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiH1ZR_VIhZeNocjI04RV7YTHtv6p68AAkG8MRvkWhhKXL9B3btDwxEBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiH2ZR_VJ78cUYlXuMBi1cm6kS6d1DwAAkK8MRvkWhhKao-cjSIRmRsBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiH3ZR_VLbKmPgG0ZY5grh0ipZaOhb4AAkS8MRvkWhhKzPbcmxZaq5EBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiH4ZR_VMk-Efq9AwWwFBU0Udx1K604AAkW8MRvkWhhKcZReB830FLABAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiH5ZR_VNwwmaInSjOv16cAU1XBhYh8AAka8MRvkWhhKjAvqMUolGeUBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiH6ZR_VPDniR6RW-8KSRJVBjOO7GQUAAlK8MRvkWhhK1-kgja6rx6ABAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiH7ZR_VQm2A1u9SbhaDdId9RPyt2SAAAlO8MRvkWhhK4z3Y9rzaMZoBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiH8ZR_VRwp-FF62tT0PdLkuxKbH1TAAAlS8MRvkWhhKPfCtg6U5fRoBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiH9ZR_VTIc2VWcFs_Ulz7Ubif69Ft4AAle8MRvkWhhKXN30K8SfI6MBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiH-ZR_VUUwoiNDf-t4ZDXEwFGxUNSYAAli8MRvkWhhK5aOSFkIaDDMBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIAAWUf1Vbdq34a7yt7Wi4UCipFJSesAAJZvDEb5FoYSpTqoGjpae2WAQADAgADeAADMAQ',
'AgACAgIAAx0CZQN7rQABAlNDZTJccu9TLiYiDNNSksc5L1j-nZMAAurSMRsDXZlJQu7l-lgYeOIBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiICZR_VYTJWNEszbtHXzdo_qAXBzb0AAl68MRvkWhhKfDUvKGGRrJcBAAMCAAN4AAMwBA',
'AgACAgIAAx0CZQN7rQABAlNKZTJcpAWF4W29akUsjcnV_-ZMkhsAAuvSMRsDXZlJUIGLqSFNNegBAAMCAAN5AAMwBA',
'AgACAgIAAx0CZQN7rQABAlN0ZTJezH9KR9xNxu6X5L7JfhQEg9MAAgTTMRsDXZlJcQ71aIExqnQBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIFZR_VcA70ScTwBCJhQ7820ooOW-IAAl--MRvkh7hL8IsHk3BxldUBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIGZR_VdbOEoil4LXucX1SpGuFW7WQAAim9MRvKVClLa2S8AAHYX84kAQADAgADeQADMAQ',
'AgACAgIAAx0EZQN7rQABAiIHZR_VevYl45qNsZBfgqTM0VqQPK4AAmPAMRv2GElLnq9DvVxIrZ8BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIIZR_VgHJVqt55pbGsuA64x0qeeusAAqHBMRv2GElLdyyVIPJma88BAAMCAAN5AAMwBA',
'AgACAgIAAx0CZQN7rQABAiOsZSBHv7Phio0sDni4et6KnUOpBxcAAh_QMRsFbQABSYaOtjgGjAQJAQADAgADeQADMAQ',
'AgACAgIAAx0EZQN7rQABAiIKZR_VitOPBeiqxuRy3Bt1PXMP0gwAAgfHMRsQI2FLoemWSiheRlgBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiILZR_VjxGRtHQAAQa6L9Bsqaq8zr-DAAIfxjEbhQ5ASyPl1jCkki9hAQADAgADeQADMAQ',
'AgACAgIAAx0CZQN7rQABAlNkZTJeTBQSmHcb-MtY5TNGHF8v51IAAvfSMRsDXZlJY2sa_KTfsx8BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiINZR_VmtAelNWukP9HQlvYBqnG3kQAAka3MRtEeVBLnNPVqAsQDo4BAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIOZR_Vn94Edsn8lwFLhVXljfgBhu0AAmW6MRvEfOhKDRySczOmld0BAAMCAAN5AAMwBA', 
'AgACAgIAAx0EZQN7rQABAiIPZR_VpAP9V8J3eISj3u3gW4JN8DIAAhzEMRt61PFLuiGdR8RIZXwBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIQZR_VqT_pKXZSUs4OICgP6cWJpgIAAh3EMRt61PFLx6J2L_bf_SABAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIRZR_Vrvke-Tp16lfL5_PXCf8L6E8AAj7BMRv3rylLMguwpNHEOZwBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiISZR_VtKlklWzldgFWWi-me5yfBHkAAnXBMRsj7LFKbSvLpn_ydnYBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiITZR_VuX5yqwABuZMvhAZln37bAvv1AAKExTEbRQ05Sgop8-r_b_E0AQADAgADeQADMAQ'
]

elite_photos = [
'AgACAgIAAx0EZQN7rQABAiIUZR_VvgN2JGL_I2XvCwnNtUTdJvIAAgi_MRuPljFIFIYnCLF91jwBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIVZR_Vw7DzlIWNl7JYzGJCznz2gbMAApS-MRswYShK3UkAAUAda6lQAQADAgADeAADMAQ',
'AgACAgIAAx0EZQN7rQABAiIWZR_VyGvH-hN-gXYjdXWsnQ-NsmUAApW-MRswYShK2jYIPwXJOegBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIXZR_VzpEfIS6puBexgHJXXKSvzdEAAp2-MRswYShKXyq9pxDVGbcBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIYZR_V01ZBHXzMVwxgnkEqiIq3ydYAAqG-MRswYShKsc8d3JoTvjUBAAMCAAN5AAMwBA',
'AgACAgIAAx0CZQN7rQABAlYEZTLtqxn0-AasERNOV33DfbpPr6cAArTXMRsDXZlJdBMoVQnOl9cBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIbZR_V3YifLKTncLeooMpzw3rhjmAAAqW-MRswYShK3KKnPs2YLs8BAAMCAAN5AAMwBA',
'AgACAgIAAx0CZQN7rQABAiORZSBEWCGtJdQwUCdFPwlOD3qxh9EAApTTMRvO2OhI2_-g0O3IOwcBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIdZR_V6LFFz-kQ8teQEuUpKum8vUQAApHBMRswYTBK3FnabmrZ3-8BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIeZR_V7a2RBhrjCMy6h4F5j9ftKk4AAqK8MRsNsjhKVLZVAAEYdOLJAQADAgADeAADMAQ',
'AgACAgIAAx0CZQN7rQABAiOTZSBEmceGNkItQft0m6iPWA8anNMAAojNMRvDqQhJ3h8fGp5kqyQBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIgZR_V9-KA1gsEQyiBvS82MXQom5YAAiq8MRuiHRBLgvBv5ODSx34BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIhZR_V_DVYRW4irUI_sPzg-tX7-C8AAg69MRuiHSBL_kvpQxZZjnQBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIiZR_WAnAfKMHQ3HVZSYi82yfcSkEAAhG9MRuiHSBLWjK5bAPbINgBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIjZR_WB6P6zZ78K9su8FQhiec6bMEAAkO7MRuTSDBLelXc_xgs2jsBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIkZR_WDOG2fMauW87FLRoUr_tojIgAAkq7MRuTSDBLzMy5pJarHb8BAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIlZR_WEdolyrNwm4DPFqnZ3AZcPhAAAu-6MRuTSDhLWR0n8mfimZYBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiImZR_WFvIPyvD8tNtxG5pzT4Ja-XcAAtC8MRuTSDhLGX8iTJuy5pIBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiInZR_WHJ8_Mi-OMj968Y5FgDZZ3mkAAiy8MRuTSEBLyiJRq5R1w-gBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIoZR_WIXtwzEcrQVfvejSIkD-CDhsAAr-9MRsig0lLdQom0zdgc2ABAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIpZR_WJrdMdxaD0tDT4b7a9xZcJy0AAsC9MRsig0lLORDqtyvbUMIBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIqZR_WKy11Jwh2XUCqZKHDiyIswFIAAqu-MRtuX0lLRydfApxsc_sBAAMCAAN5AAMwBA',
'AgACAgIAAx0CZQN7rQABAlXfZTLcX4dH6oWXoH4evg5BVb2SMNAAAoHXMRsDXZlJLmwYpCN9FqsBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIsZR_WNlygeZUybowsRpv2Z8ukOz0AAnm-MRsig0lLUmXsMe8aZUgBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiItZR_WO81C-OY1BYGc2UWFsO6EHJwAAn6-MRsig0lLwGzD0RrxOKQBAAMCAAN4AAMwBA',
'AgACAgIAAx0CZQN7rQABAlYBZTLtK67-zHCesAmudPFVRMJ7Jx4AArPXMRsDXZlJPK3FumrJdjIBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIvZR_WRVoKriTz15AqvwlxxtuNKOMAAtW-MRt0SWlL9vQa9EDxESgBAAMCAAN5AAMwBA',
'AgACAgIAAx0CZQN7rQABAlYLZTLwNAwx1vPzySwZW_DVyCpy8kwAAr7XMRsDXZlJirA_q9TktfoBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiIxZR_WULz643463LXuo8YKUKA4yDIAAuu8MRvNUrlLJiq0b5nV1VsBAAMCAAN4AAMwBA',
'AgACAgEAAx0CZQN7rQABAiOXZSBE9_16O-efOcxgPQuYra4pGPYAAkasMRv2LYBE65bvIVD7GQABAQADAgADeQADMAQ',
'AgACAgIAAx0EZQN7rQABAiIzZR_WWmkTv64FXV8mC0nWL0DTNAcAAqzCMRvNUsFLag6glM-9X3EBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiI0ZR_WX3V1wblBL4z9B0k7cNk04n0AAr_CMRvNUsFLPAVWPigvHr4BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiI1ZR_WZKL66rvTUUZHbSve5SR6rOYAAsPCMRvNUsFLqoiGx1XQKn8BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiI2ZR_Wao2A1WY-F9L-LpyYz_FrO7YAAszCMRvNUsFL7duhZ1LbIf4BAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiI3ZR_Wb-AasgZDxNUaa7qy67lYZEMAAu3CMRvNUsFLQyp7D5vjoysBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiI4ZR_WdFwN5n3_BllD8R_Jz247rtQAAki7MRuTSDBLB5h1X-M-ETYBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiI5ZR_WeU8jqwFaTJkDPlOd8-BXpSkAAoe9MRsNsjhKSQ6eFFHG1uYBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiI7ZR_WfsbLh4kmMg1d9qY_fH5LXkcAAtC8MRtJWelLnvsZruUTfxIBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiI8ZR_WhCV776lkHCT38BY87BksrfkAAjHAMRsepjhIh92IWeweSlkBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiI9ZR_Wic0fSZSflLDSCn-XjxPtgnkAAgbBMRsVTshI6COnOHW8qowBAAMCAAN5AAMwBA',
'AgACAgIAAx0CZQN7rQABAiObZSBFtvD0ArjaXyOjD5IDttvLZRwAArXIMRv87ehIgRY-2zC8IdEBAAMCAAN5AAMwBA',
'AgACAgIAAx0CZQN7rQABAiOcZSBFtgTnEULfRosya0OY5kb8oMgAAn7JMRsJ56FI93gZGLBgAbQBAAMCAAN5AAMwBA',
'AgACAgIAAx0CZQN7rQABAiOnZSBGj28abG2YMdHfkLPWH44ope4AAhnQMRsFbQABSfr1U__q_05mAQADAgADeQADMAQ',
'AgACAgIAAx0EZQN7rQABAiJBZR_Wniv4OcKzFOz6thA6mmT9wjcAAje-MRv7cxFIy6g-TBeEfqABAAMCAAN5AAMwBA',
'AgACAgIAAx0CZQN7rQABAiOhZSBF-By71izIzzU-oIHRKGsPnl0AAmfOMRucqfFIRTLhQM0W-uQBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJDZR_WqCyXZxB0plNqHQABk-OcEQnNAAInwzEbGS1YSjeEGRayENFrAQADAgADeAADMAQ',
'AgACAgIAAx0EZQN7rQABAiJEZR_WrQABskqQorON7HLMhuZuNvXuAAJ3vTEbwuOhSuEYVotHIlTRAQADAgADeQADMAQ',
'AgACAgIAAx0EZQN7rQABAiJFZR_WshxpdSlHDYbGJPitqX8EiAkAAr2_MRsnIpFKLjwkuSbYThABAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJGZR_Wt0X77Jqj42TY9sY4njWp6SkAAtPEMRt61OlL7nybCXfe7OsBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJHZR_WvQkVlNL0dqSuXsFRoDi02rkAAnLQMRuQZtlKUsFBzGHioHsBAAMCAAN4AAMwBA',
'AgACAgIAAx0CZQN7rQABAlX-ZTLsLD1A7Onx9fm9JSWvR_8JOPwAAq_XMRsDXZlJNM2SxK50hfMBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJJZR_Wx8_8_Jqm8JTVf54atytDYz0AArbEMRt61OlLQU9QqV29n54BAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJKZR_WzE7Ke1B94XVzsw4-CPf6AnQAAhnFMRsCcqhKNT_zl20OsU8BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJLZR_W0k0jhSKzjnWFTAAB2z40OqFlAALOwTEbzuWQSusGU9ykg8bdAQADAgADeQADMAQ',
'AgACAgIAAx0EZQN7rQABAiJMZR_W1y7PHNVUHCNtobQDpCuJXQwAApm8MRtsjbBJnQR_7KMs_0MBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJNZR_W3Ff4Z8WxG_cDIno26OA_2hgAAs_BMRt8LqlJcyVFCVDnqYkBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJOZR_W4bvy4yuhk9hsJ3dR6mDb1N4AAj3FMRtGbWlLUDfAd7JEt48BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJPZR_W5tupsgdWPqM-R5VcHFS7iZYAAgHIMRvtLQABSLkm6yJThvoIAQADAgADeQADMAQ',
'AgACAgIAAx0CZQN7rQABAlOSZTJft5p7CKfzLw0BSgvz3ZUEidkAAg3TMRsDXZlJa5VqbGnc0bUBAAMCAAN5AAMwBA',
'AgACAgIAAx0CZQN7rQABAlymZTQpCMAzHKXs-oIoTFRcZ2mn88EAAszQMRughaBJBxsXUoSwZsYBAAMCAAN5AAMwBA'
]

ero_photos = [
'AgACAgIAAx0EZQN7rQABAiJQZR_W6-Yg16atV2an_gguMvWGxnMAApa-MRswYShKvGpX6pVvGBQBAAMCAAN5AAMwBA',
'AgACAgIAAx0CZQN7rQABAiOHZSBBpcsBCpSbg1fo06AUvwNWPIMAAhvKMRs7-5lJYQ2Tvox7j-cBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJSZR_W9mpvxAN4OsABwO0G1K_vbCkAAgW7MRuTSDBLyz-uwEAF1asBAAMCAAN5AAMwBA',
'AgACAgIAAx0CZQN7rQABAiOJZSBCTtI52gbFHZyUFafKNbhAnb0AAgzUMRvFINBI5PyyXOyjp6wBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJUZR_XAAFFC8FEJk-g0ZVFV_s7B8sPAAL8vDEboh0gS3-M1alwKfFHAQADAgADeQADMAQ',
'AgACAgIAAx0EZQN7rQABAiJVZR_XBQolqf8Re25JNJxS2TLKdQEAAhO7MRuTSDBL5i25I6dRSYUBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJWZR_XC1lslKE2QgABWsYesRyZHWCYAAIVuzEbk0gwS8rVjMJkoDXVAQADAgADeQADMAQ',
'AgACAgIAAx0EZQN7rQABAiJYZR_XEO1mfUicg0iqReuh0fdCyv4AAk67MRuTSDBLntyXT2SXabIBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJZZR_XFbBjG0pAPAvxwb-Ly4QZTrcAAlO7MRuTSDBL9EXPIsHTjIUBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJaZR_XG9r-e30Vmyp1hfCxj-Ic4ZQAAme7MRuTSDBLrDrfqwSEx7YBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJbZR_XIKaO4p5OS1Cc38M7kZN21WUAAna7MRuTSDBLGFkuZsg5t3QBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJcZR_XJSw0XsgdwMwgEPVxvu12nOYAAom8MRvQBdBKoE2_bDMycLYBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJdZR_XKjvjods-k0Z19Bp5ktzm1WoAAoO7MRuTSDBLawq2mqGF_W4BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJeZR_XL1bXVeZ9zOca4guloi9ju2AAAom7MRuTSDBL9IgxNPM2SqUBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJfZR_XNBY4WrOxGTAj3X3AMZpXMRsAAva6MRuTSDhLzqyKZ1YE7toBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJgZR_XOnSQvOrumd_3WGhkGWiK3uQAAmGvMRt4aWlJZx4xlfb-6o8BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJhZR_XP4Z1klyzDkrSmuk6KUXLIkMAAgS-MRsulaFI4PQ67JSYGGwBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJiZR_XRFvITnbDSpXGb4wQyrAfRU8AAlexMRt1XRlJxUeQsB0M_nsBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJjZR_XSesNvaeP30hiR40zd57zuAIAAju8MRuTSEBLjtCtoYsbOPABAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJkZR_XTuZz88ra4cjOaWoVKBM8p8EAArW9MRsig0lLvEVdvHi8AqQBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJlZR_XVGOMGOfxFV9G_70C4MmDjE0AAqa_MRtb5nBLqXBpZBbzu0IBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJmZR_XWUcMP31clcpArXlDQlOHPpwAAqDAMRs5CwhKdIg-ptwDKscBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJnZR_XXu8IQ5s_hCXHQQZrJlrPNNIAAvm7MRuQnfFJKPUR9N1YfMcBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJoZR_XY0Ea8NWlAxE80YFP9xTsqMQAAiHDMRu7LEFL9f6rAcutvo0BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJpZR_XaJNvMj65jLlQHuMMqE61h-wAAhTDMRvkgZFLDEtEUimu79IBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJqZR_XbhIVx0xTqK4DzoLZVQvXSMYAAsK-MRscv5BLC771fCGPRPABAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJrZR_Xc60wPwLh_9bKjxumi8zM7dwAAuG8MRvNUrlL-z9RCfkur0wBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJsZR_XeAeoWEzxptnZGlAI8k_xozsAAue8MRvNUrlLv0Jtsn9ZwwUBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJtZR_XfTlWmXAMOxrY9cGLXd50HqIAAu-8MRvNUrlLdqDR2t4VrQcBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJuZR_Xg4C7Bn1uurBlkXy-cpf_ligAArGrMRvurVlLjzpbd1KxBfYBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJvZR_XiNqVAuqX8B1Vc4FQWH-8o08AAnSsMRstFohLmU2YCFG4Lw0BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJwZR_XjVkOeTWpSnB0XE0Dt_xzc3YAAvS8MRvNUrlLnQ5Pr0Kn5vMBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJxZR_XkoxnXKA6NkzgqsPLGQHWRJIAApXAMRtlBbhLwdgZ5WDsFUcBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJyZR_XmAVsJzJ8xXh52mf5k8bVQ9gAAqrCMRvNUsFL8QABcSKFay0dAQADAgADeQADMAQ',
'AgACAgIAAx0EZQN7rQABAiJzZR_XnRRk3i3-kFxg64RL4hvHmYMAAr3CMRvNUsFLR8svGa_tFqQBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJ0ZR_Xot1VYG9vv3yOoLAb5i454jkAAp6-MRt7uhlLoMcoKwq9v0sBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJ1ZR_Xp_xIXj4KfHWOz8IJGGyLoXMAArOuMRsYBXBL36VQGs8BvDkBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJ3ZR_XrAABoDrDw_5kb97oAe_vZxftAAKpvjEbBzkpSDtlUU0OXYT9AQADAgADeQADMAQ',
'AgACAgIAAx0CZQN7rQABAiONZSBC1VwODIh0o1vTlwa5lXvGbKUAAqbRMRuwBtBKPl5-dETwTrwBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJ5ZR_Xt276gEnrY_jipbnClrGsdfEAAgS_MRsICZhIWXYVdzeg8w8BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJ6ZR_XvEwe5KPk3scufIRln6ceo70AAq26MRtdfElITwIkqhcUWtsBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJ7ZR_XwTYN-9yTvrnyvdmt0m_ajMgAAkHAMRvKwjFJQtc7BlIAAWnuAQADAgADeQADMAQ',
'AgACAgIAAx0EZQN7rQABAiJ8ZR_XxlDhd62EniBB1mxYenWY2j4AAkLAMRvKwjFJNbYAAr7ur58BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJ9ZR_XzFetDC6_qbbERtrPBLBAK14AAkPAMRvKwjFJb8ogmGAuogQBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJ-ZR_X0eoF6dUvxTk8NK_73lqbwaEAAkTAMRvKwjFJxzhEtXaUtD0BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiJ_ZR_X1st4ySNFBH456VZFw_EI07EAAgK5MRuu-_lJeNALd9eYpCgBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKAZR_X2yKyQ5M4FBc8e5WFjaXoKUwAAqzAMRuS1glKzIll1mv32g8BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKBZR_X4Oo09hFP4gnN8qEQjRIoVJMAAn3SMRtAGphKGOzsIRuyVHUBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKCZR_X5oB4wID5f6k5Un6yUH15DGIAAn7SMRtAGphKtvoknQKACiQBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKDZR_X6_6eKjFMPwTGnK_EYNsIMSEAAjbCMRtv4tBK5goklZa2YwEBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKEZR_X8AOPij1yc9XF4PaAMSZqJDkAAivBMRt87NlID9-lEvy0KWIBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKFZR_X9dqYLI1HDOtKv4NNHr8I9vIAAtfEMRt61OlLW7BjLvRivioBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKGZR_X-tg1WlUGhUBRgPG1zqTo884AAgPEMRukpBhLWCiQpyhSj94BAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKHZR_X_ziPbeKJZoWafA5YehRbtuoAAs-9MRsUFElI0GqRk4CtcSIBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKIZR_YBTncck-njMedU9J7jFbmNqsAArrGMRs1Z0FJikZc9EMlQKcBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKJZR_YCoRlagdDiqHu_9mjoZS1j6IAAlTCMRu36qlKK-6Y2fYuvTYBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKKZR_YD7PLPkdiPNwmubyd9OBVfFkAAt_HMRutvvFKs01ZIJBboioBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKLZR_YFOCz90bdE_If83vCO4bA_ucAArfBMRuMOrhJx2nBH-9cnxkBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKMZR_YGecBS3NTkHZuTFsgD7nmR00AAnPAMRsMb2BI_C1ndBWwqEQBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKNZR_YH8IojBiPBf5o_wAB4Axm4w94AAIwwTEbjtW5S8Nfv08Tbu3FAQADAgADeQADMAQ',
'AgACAgIAAx0EZQN7rQABAiKOZR_YJLCdNsq0PHK9cMs2oCxJSxUAAn7BMRuIDdFKu8NrOZKpQssBAAMCAAN5AAMwBA',
'AgACAgEAAx0EZQN7rQABAiKPZR_YKafy3G6jqnK-pdKHNud76GIAAgWrMRtq7PFH-4F5tg9N93MBAAMCAAN5AAMwBA'
]

arc_photos = [
'AgACAgIAAx0CZQN7rQACokZixQeMNfeQtA9uVWkRZkmoe5HNmwACor4xGzBhKEpLsoWWF_DvCgEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxIVi97yjwhQO4zT942exyiuBqg0NEgACxcIxG81SwUuOxg35gJjW0wEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxL5i97_NhthzIxc4g6LWaHiH2UWidwAC28IxG81SwUvmWDuX0pTvRgEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxMNi98SNTey1aRpK4jx9j8mYOCE5eQAC58IxG81SwUsTApbeHSSTYgEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxMli98ZngzfMQpGh6PfZrNRHS8Cz2QAC8cIxG81SwUvbtMx54_NFIgEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxMti98iMLRlyq9i0Bth0Xd2v4suhBwAC9MIxG81SwUvnrkEuneci0QEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxM9i98jqtXZ-2kON5ZzpTrlumJGU5QAC9sIxG81SwUv9RzI0su7VkAEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxNNi98lBwsOfCrnYXaJ67RkamAElKwAC-MIxG81SwUsqRlDPioaSdwEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxNdi9877JDRQyuKvqijT_WE6zlzfRgAC_MIxG81SwUsZ77r8SnGoYgEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxNli98_ctmO0tb4PyoiQwEnGq2QW5wAC_sIxG81SwUsdT0lLlKg6MAEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxNti99BKlvPcIb5klwV7BsH3rKH_YAAC_8IxG81SwUtKCX58FQLTugEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQAC1aFjV8Tl7Ig-DH4-tLtn5U2FUFxfAAM4wTEbb-LASvzC_7fzJMW8AQADAgADcwADKgQ',
'AgACAgIAAx0CZQN7rQACxOFi99Tp8IDcvQMqqwNWJ-HFwEzg6QACDMMxG81SwUtuw0fyPnpH0wEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxONi99UY0-Q-M2yQ-xXapfmFQywvuwACDcMxG81SwUvmrNjeYB_CXgEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxOVi99Xzua7h1DHOVk7EOuRyN2-tpgACEMMxG81SwUvuh-CdlLe5ZwEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxOhi99bsaQABXo0n5KrPhAzcqg0NKj0AAhbDMRvNUsFLDr7zNJnc0NwBAAMCAANzAAMpBA',
'AgACAgIAAx0CZQN7rQACxOpi99cew6Ko2GtN-SDRDsLzHvGOfQACF8MxG81SwUvqoSpjDxGvwAEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxOxi99dc0ef0IWelQwbmouurrAK-BQACGcMxG81SwUv0jd45hLgxrAEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxO5i99esFbZA3mMOhVpRp33zdOpmXQACGsMxG81SwUtsngxPDTIxwwEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxPJi99q07_UYg11JAAEkOShbgSZ1EhEAAoPDMRvNUsFLKKB3oCfG6rMBAAMCAANzAAMpBA',
'AgACAgIAAx0CZQN7rQACxPVi99sGejVLX-AGGHAf4taUu_GBHwAChsMxG81SwUv8Cp8vibeQRQEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxPdi99wao1l5OZWUHijOTJnKvBcECQACh8MxG81SwUsC4JDQA6dc9QEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxPli99xFF4faVeaEJ8-CWiAUtNBlCwACicMxG81SwUuW6R5wVSFq3wEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxPti99xe-eET7TUhfejF12knbp5OhwACisMxG81SwUvl9S6jigT7_AEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxP1i9933jXCRoYYm7uiJx1aBzhrvdwACkcMxG81SwUsm5kNAgpkFbAEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxP9i995QJ8FNjkGcn9ihWGTxpTpwKQACksMxG81SwUvs6XQKQYNEmwEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxQFi997BVNmt1-TAYJaGRx2Js_HshQACk8MxG81SwUsvPK-5T5WEEQEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxQVi9-AIC8cirTG43vumpGf39sfQwQACG74xGyOiwEsSut5yefTFCgEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxQdi9-BhiEfoLHmBfaAR9SKH_xx7kwAClsMxG81SwUtKUeS9gZ80SQEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACxQli9-D7dlI0pJeO4S7-HxGuvfKcbAACm8MxG81SwUuf9w1RYAeHRQEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQACsS9i5TGo2RlCU0hQuWCj4kn0qEAcTQACTb8xG2fEKUsbBWj_0YATnQEAAwIAA3MAAykE',
'AgACAgQAAx0CZQN7rQACzL5jJeksrJ-jFAZ-L_1ADENJc4rWfAACSK4xG_Aw9VOT4EUVPdC8qAEAAwIAA3MAAykE',
'AgACAgQAAx0CZQN7rQACzL9jJeksOVBz3Rwcg1ft13the_lFmQACi7gxG4eLeFEUTdIfDXRMkQEAAwIAA3MAAykE',
'AgACAgIAAx0CZQN7rQAC1UBjV5IAAWHrrhzwHggJ4pTqEaYI7PMAArS-MRtYU8BKD9cHdkQG7PMBAAMCAANzAAMqBA',
'AgACAgIAAx0CZQN7rQAC1YljV7CW18XqLN5Dy7-JCcrWb_TGawACycAxG2_iwErUKa_BHgm-jgEAAwIAA3MAAyoE',
'AgACAgIAAx0CZQN7rQAC1YxjV7KRKuacUKVsZq8PPmqfRtZNSwAC6MAxG2_iwEraoeQu0HmvmwEAAwIAA3MAAyoE',
'AgACAgIAAx0CZQN7rQAC1Y9jV7MnyMcl9TYbabLN7n6SxEJ23AAC7sAxG2_iwEqxhK-koWO-NQEAAwIAA3MAAyoE',
'AgACAgIAAx0CZQN7rQAC1ZJjV7SAoFi1zXHA2VFWfANOCpDIowAC-8AxG2_iwErcpiUljRJQZQEAAwIAA3MAAyoE',
'AgACAgIAAx0CZQN7rQAC1ZljV8RASmssbk28AeE19Ta-bj-nDgACM8ExG2_iwEp6GJrjyWlfjwEAAwIAA3MAAyoE',
'AgACAgIAAx0CZQN7rQAC1ZljV8RASmssbk28AeE19Ta-bj-nDgACM8ExG2_iwEp6GJrjyWlfjwEAAwIAA3MAAyoE',
'AgACAgIAAx0CZQN7rQAC1adjV8Z46-yLkfxziquOuTT5CbL75gACQcExG2_iwEqAZoYZfUDy6AEAAwIAA3MAAyoE',
'AgACAgIAAx0CZQN7rQAC1aljV8bOS61xGsmTeUiz-nNfm6gorQACQsExG2_iwEoCERRNtpQhTwEAAwIAA3MAAyoE'
]

trap_photos = [
'AgACAgIAAx0EZQN7rQABAiKQZR_YLgz1e2qCV3pK9PSCTa8gaE8AAqDCMRsZLVBKXX-OUpZn1gMBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKRZR_YM4qjASxURESLJdjVSrEItHEAAqHCMRsZLVBKXCy9v0fZMaMBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKSZR_YOXY_BDcRIIVFDBEU1pzw8J8AAh3DMRsZLVhKytcvY_Ve5koBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKUZR_YPrUQjTyFxWf4xoUyL73qbxEAAh7DMRsZLVhKGiboX276XU4BAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKVZR_YQ3I_m1FUsM0ui3NkIF47pXQAAiXDMRsZLVhK2CKbk7dxSiMBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKWZR_YSDk_O9aPnK9DWm2wZ7k1hjUAAizDMRsZLVhKGv89VPoUd2kBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKXZR_YTYj2-xrMdKRl_ciCJ5yHxzsAAjTDMRsZLVhKDiCteHhWCE4BAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKYZR_YUgyrTAfRQdX4qdYria9A6BMAAjnDMRsZLVhKv01WljjKNBsBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKZZR_YWCjICeZGj2ECu-Uf-k-S76oAAlLDMRsZLVhKJMY4ivBVn7oBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKaZR_YXbKikPVq4wPZcdbpV4nmkJcAAlnDMRsZLVhK_q7bCd8OotUBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKbZR_YYuCFPqFjcsIqORcM8zrZkSsAAinDMRsZLVhK5uvNS8dbnlQBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKcZR_YZyDTm8o90drmCjXsYYeYOoQAAl7DMRsZLVhKv3T7lMa4gHIBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKdZR_YbJQXkh99JJsZ7LsLHMwROVgAAm3DMRsZLVhKjaivb2Oxs6gBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKeZR_YciGlY3cyB5_xcFA_eKnFOFUAAmu_MRu0UWlKF2dmCD1fwIMBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKfZR_Yd1Nn-5XKZHL3pcGYkPOrDEEAAifDMRvGNmhKA8joufo2k3QBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKgZR_YfMIO41WVIO5myCgKrqwc7_kAAinDMRvGNmhKwGdMntSz5-YBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKhZR_YgfEdoOveIiU6VxRrYtl6TocAAhvEMRvGNmhKGE0S9wRQZwMBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKiZR_YhpnSlC2GRD9H0vhNe1bqg-gAAnPSMRtAGphKyb-2NyvJhHIBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKjZR_YjLVQKOh8-QEVe0NMvw_ii6gAAj7BMRtv4sBKIh8kHit8VaQBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKkZR_YkdN1V8A2G9VI4EqJVzJSRBoAAgTFMRt61OlLRa_1-cPTsjABAAMCAAN4AAMwBA',
'AgACAgIAAx0CZQN7rQABAiNkZSAzfz7Ky09eimKxcrVMjvxqP8wAApvPMRsFbQABSe92u0UeMtQ2AQADAgADeAADMAQ',
'AgACAgIAAx0EZQN7rQABAiKmZR_Ym7CYJoJiLA6OxMUPBvOOc3IAAkDEMRt61PFLYO9JcHbakHkBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKnZR_YoQkzWMIsmONUUbrHbWtZb1AAAkHEMRt61PFLIFhBMdPOmnABAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKoZR_YptzZWI2sXOODWM3IGHQjk4QAAkLEMRt61PFLLpEgCKN2W7UBAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKpZR_Yq-15GOnG33n5P8FXmYKgVbIAAkPEMRt61PFLBS9hCQABp-zyAQADAgADeQADMAQ',
'AgACAgIAAx0EZQN7rQABAiKqZR_YsCuDuPD3aRGvIHAanjoOvvcAAkTEMRt61PFL9XL7kFXNjBcBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKrZR_Ytd61MvFbWyTpD1olQb39pJAAAkXEMRt61PFLPgAB5q_tz6H6AQADAgADeQADMAQ',
'AgACAgIAAx0EZQN7rQABAiKsZR_Yuyjo-rNJcRUBE46Gk5G1wWcAAkbEMRt61PFLofns37-RBy4BAAMCAAN4AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKtZR_YwHP5FIAa5qnt4lE1rvyRFKAAAkjEMRt61PFLBrz6pJuDNiQBAAMCAAN5AAMwBA',
'AgACAgIAAx0EZQN7rQABAiKuZR_YxcJ_8wOjFb7iRwVf_H_HiR4AAknEMRt61PFLJEEsP0PY3XcBAAMCAAN4AAMwBA',
'AgACAgIAAx0CZQN7rQABAiN9ZSA-toVFKb7SVcLqaagqMEZ0-68AAurPMRsFbQABSdCF2E27_bluAQADAgADeAADMAQ',
'AgACAgIAAx0CZQN7rQABAiOBZSA_8nzaHbUllkv3fc4Y5M-3ep8AAvvPMRsFbQABSd9eySoMlbpSAQADAgADeQADMAQ',
'AgACAgIAAx0CZQN7rQABAlReZTKRNKA51H6yZMr9meMkClve1XQAAkPUMRsDXZlJwHbkVESusMoBAAMCAAN5AAMwBA'
]

casino_pics = {
'🍉 🍉 🍉': 'AgACAgIAAx0EZQN7rQAC5bRkBOrj2S481ud3r_NOagHuohRB-wACv8ExG-P56UpbIES4RuQE8AEAAwIAA3kAAy4E',
'🍉 🍉 🍓': 'AgACAgIAAx0EZQN7rQAC5bVkBOrnsVvsp4X_PaLxBYpbhQ8QkQACF8ExG8hrMUs6ig1zcR6mEQEAAwIAA3kAAy4E',
'🍉 🍉 🍒': 'AgACAgIAAx0EZQN7rQAC5bZkBOrrWLAHhjhLeDnHDRwXmKXEfAACFsExG8hrMUvzkiV79uMAAfkBAAMCAAN5AAMuBA',
'🍉 🍉 🍋': 'AgACAgIAAx0EZQN7rQAC5bdkBOru3vKbaypNlau1QCX2-C3YHAACvcExG-P56UqIY0YvU9TMUwEAAwIAA3kAAy4E',
'🍉 🍓 🍉': 'AgACAgIAAx0EZQN7rQAC5bhkBOrylq_PcT1AqIiFvrEnqzo12AACDMExG8hrMUub6C2lMTcr5wEAAwIAA3kAAy4E',
'🍉 🍓 🍓': 'AgACAgIAAx0EZQN7rQAC5blkBOr2Y_hl4cd_uDYzH6qjeUI5SQACwcExG-P56UrqTjw8kW9fZAEAAwIAA3kAAy4E',
'🍉 🍓 🍒': 'AgACAgIAAx0EZQN7rQAC5bpkBOr5Dj9j46ZxyMKLcIbuo0j4NQACL8ExG8hrMUvdhpGi62DwNgEAAwIAA3kAAy4E',
'🍉 🍓 🍋': 'AgACAgIAAx0EZQN7rQAC5btkBOr9hQYqEHWSZxwEG755iG_hTwACGsExG8hrMUtkFNOWSOiUVgEAAwIAA3kAAy4E',
'🍉 🍒 🍉': 'AgACAgIAAx0EZQN7rQAC5bxkBOsBy_prChEtgAu81RaLlJ5gIQACIsExG8hrMUshGRHW2AJG0AEAAwIAA3kAAy4E',
'🍉 🍒 🍓': 'AgACAgIAAx0EZQN7rQAC5b1kBOsFRWoX4XQZFli1c0bQLkEvqwACE8ExG8hrMUvSfctrNeHGTAEAAwIAA3kAAy4E',
'🍉 🍒 🍒': 'AgACAgIAAx0EZQN7rQAC5b5kBOsIXQdKUHBVDuntQx2CjG6ksQACxsExG-P56UoqfTLA2PmFNAEAAwIAA3kAAy4E',
'🍉 🍒 🍋': 'AgACAgIAAx0EZQN7rQAC5b9kBOsMhKxBk_kVyW2jJTXtoLPpDQACEMExG8hrMUt6AAEL9KDybY8BAAMCAAN5AAMuBA',
'🍉 🍋 🍉': 'AgACAgIAAx0EZQN7rQAC5cBkBOsQ6R0JInLahlDMsTGaVDqtnAACJcExG8hrMUs6xbT_emCOvAEAAwIAA3kAAy4E',
'🍉 🍋 🍓': 'AgACAgIAAx0EZQN7rQAC5cFkBOsTCFzQmxSJ0RO2oVjA-vwfygACKcExG8hrMUsx2OUsBuZIYwEAAwIAA3kAAy4E',
'🍉 🍋 🍒': 'AgACAgIAAx0EZQN7rQAC5cJkBOsXdLyh9XDXlc0ZEMtz92axlgACJ8ExG8hrMUtWo4VxLSqBowEAAwIAA3kAAy4E',
'🍉 🍋 🍋': 'AgACAgIAAx0EZQN7rQAC5cNkBOsbJbQMNDPOCL5wi2RJb2rt3QACJMExG8hrMUvwf80Xa5RoIAEAAwIAA3kAAy4E',
'🍓 🍉 🍉': 'AgACAgIAAx0EZQN7rQAC5cRkBOse04k_SPSbEJ1iIREqEEqFHAACKMExG8hrMUtDmtxOsHYLNAEAAwIAA3kAAy4E',
'🍓 🍉 🍓': 'AgACAgIAAx0EZQN7rQAC5cVkBOsiEkETt72BxrRSDLqoRfklwgACIMExG8hrMUvAtzHTqNNmewEAAwIAA3kAAy4E',
'🍓 🍉 🍒': 'AgACAgIAAx0EZQN7rQAC5cZkBOslp3BLo3wXyPB5BbOY0rxk9AACi8UxG26MkUu1yftX_OXBkwEAAwIAA3kAAy4E',
'🍓 🍉 🍋': 'AgACAgIAAx0EZQN7rQAC5cdkBOspvMkPGiO4u_7ofNkQBiEU_QACs8ExG-P56UooyOnxNmdS5AEAAwIAA3kAAy4E',
'🍓 🍓 🍉': 'AgACAgIAAx0EZQN7rQAC5chkBOsth2907HbJFMZVs_BtiiQYhgACysExG-P56UqELbVC8pCEpgEAAwIAA3kAAy4E',
'🍓 🍓 🍓': 'AgACAgIAAx0EZQN7rQAC5clkBOswARg_9qy6n1Mv5QJHbczkZQACH8ExG8hrMUtFa5AVECEuRQEAAwIAA3kAAy4E',
'🍓 🍓 🍒': 'AgACAgIAAx0EZQN7rQAC5cpkBOs0tQdDyjO3BZp5G3u9X3Y47wACrsExG-P56Uq8K-g-aXDwAgEAAwIAA3kAAy4E',
'🍓 🍓 🍋': 'AgACAgIAAx0EZQN7rQAC5ctkBOs3xhM53aUKm4ic2wkEAQ3Z_AACvMExG-P56UqJEs0C1alMfAEAAwIAA3kAAy4E',
'🍓 🍒 🍉': 'AgACAgIAAx0EZQN7rQAC5cxkBOs7lQKpGScJ7v_UNAl5eJL8NgACI8ExG8hrMUtM7apBj6AOQgEAAwIAA3kAAy4E',
'🍓 🍒 🍓': 'AgACAgIAAx0EZQN7rQAC5c1kBOs_YecX5aQDOFNrC0m3QFlpswACHcExG8hrMUseC0Cuu8fm5AEAAwIAA3kAAy4E',
'🍓 🍒 🍒': 'AgACAgIAAx0EZQN7rQAC5c5kBOtCXy8_p1BQidhOlxbFOfzK0gACxcExG-P56UozxnZTky5mvAEAAwIAA3kAAy4E',
'🍓 🍒 🍋': 'AgACAgIAAx0EZQN7rQAC5c9kBOtGecsElkK_1j4gRj98nyhBEQACJsExG8hrMUsdUXzoefu92QEAAwIAA3kAAy4E',
'🍓 🍋 🍉': 'AgACAgIAAx0EZQN7rQAC5dBkBOtJRiyaJC4pe9_8NIpHHaFFEgACDcExG8hrMUvlGMPJ1P5EkwEAAwIAA3kAAy4E',
'🍓 🍋 🍓': 'AgACAgIAAx0EZQN7rQAC5dFkBOtN1_6-vR0EdZEUk6CuOxbTOAACuMExG-P56Uo4o_fsEFAtvAEAAwIAA3kAAy4E',
'🍓 🍋 🍒': 'AgACAgIAAx0EZQN7rQAC5dJkBOtRQonFPn0EZKfOuCDPsP106QACucExG-P56UoUG5DhSn7bIQEAAwIAA3kAAy4E',
'🍓 🍋 🍋': 'AgACAgIAAx0EZQN7rQAC5dNkBOtUpmrY9jktmVDxgCewOUasiwACEcExG8hrMUv382woTatj-QEAAwIAA3kAAy4E',
'🍒 🍉 🍉': 'AgACAgIAAx0EZQN7rQAC5dRkBOtY_4WDGjIyLLbUVUxfhSR5PgACEsExG8hrMUsUqSH05yPkqAEAAwIAA3kAAy4E',
'🍒 🍉 🍓': 'AgACAgIAAx0EZQN7rQAC5dVkBOtcwNRZ_Hw_MIUzZWnLc7NxMAACwMExG-P56UpOObeBCmiu2AEAAwIAA3kAAy4E',
'🍒 🍉 🍒': 'AgACAgIAAx0EZQN7rQAC5dZkBOtf0JbJIazLQVH9q9mXYyDr0gACssExG-P56UqA_wfnF2buJQEAAwIAA3kAAy4E',
'🍒 🍉 🍋': 'AgACAgIAAx0EZQN7rQAC5ddkBOtjbVcAAUjcjLRVU50FpnB7LGEAAhXBMRvIazFLXIIye4BPZ1IBAAMCAAN5AAMuBA',
'🍒 🍓 🍉': 'AgACAgIAAx0EZQN7rQAC5dhkBOtnAAE85w3HZYjKAAERhuUdO15MAAKtwTEb4_npSjlNmzHyDyi_AQADAgADeQADLgQ',
'🍒 🍓 🍓': 'AgACAgIAAx0EZQN7rQAC5dlkBOtrcjFbQoxuqq5iZszvswEAAQ0AAiHBMRvIazFLG7a_kIKMoqcBAAMCAAN5AAMuBA',
'🍒 🍓 🍒': 'AgACAgIAAx0EZQN7rQAC5dpkBOtu0UIpSDCCDgRfanBIW1ZYGgACG8ExG8hrMUuz95_8gknSigEAAwIAA3kAAy4E',
'🍒 🍓 🍋': 'AgACAgIAAx0EZQN7rQAC5dtkBOtyLWS6kFj9rLBV3BGerm42swACtcExG-P56Uovf1UiDBeXmAEAAwIAA3kAAy4E',
'🍒 🍒 🍉': 'AgACAgIAAx0EZQN7rQAC5dxkBOt2w7HM8TUDPL5-2XsjjVgvjgACFMExG8hrMUujDF4PqGzRzgEAAwIAA3kAAy4E',
'🍒 🍒 🍓': 'AgACAgIAAx0EZQN7rQAC5d1kBOt5SbdJgxw-RjQ1GRLhjqqhmwACD8ExG8hrMUvQWChRGsw-HwEAAwIAA3kAAy4E',
'🍒 🍒 🍒': 'AgACAgIAAx0EZQN7rQAC5d5kBOt9AZyv7ds7XgdLFY7oPqCSJgACCsExG8hrMUtAatp-E3lTpAEAAwIAA3kAAy4E',
'🍒 🍒 🍋': 'AgACAgIAAx0EZQN7rQAC5d9kBOuAdQABkXvcSSyUpgABQDe-LCZIAAIcwTEbyGsxS2Yw7hYqSw2QAQADAgADeQADLgQ',
'🍒 🍋 🍉': 'AgACAgIAAx0EZQN7rQAC5eBkBOuEXGgW0hvv2-0MuVyRMnCnnwACtMExG-P56UowwR6G8XKiwgEAAwIAA3kAAy4E',
'🍒 🍋 🍓': 'AgACAgIAAx0EZQN7rQAC5eFkBOuIsbIf-YEX1PiKnWLe6zip2wACHsExG8hrMUvRWVF4YDoZQgEAAwIAA3kAAy4E',
'🍒 🍋 🍒': 'AgACAgIAAx0EZQN7rQAC5eJkBOuL2IDl4JLU7HfBmD5OXkbNHAACwsExG-P56UpgGculfXD5RQEAAwIAA3kAAy4E',
'🍒 🍋 🍋': 'AgACAgIAAx0EZQN7rQAC5eNkBOuPxQ9A3ROjt_-Kwxv9tzMR9gACw8ExG-P56Uq8JJp1kSNV0gEAAwIAA3kAAy4E',
'🍋 🍉 🍉': 'AgACAgIAAx0EZQN7rQAC5eRkBOuTD0vos74_k_20-7bRl6uLxQACgsUxG26MkUtfJq1ahYJdTgEAAwIAA3kAAy4E',
'🍋 🍉 🍓': 'AgACAgIAAx0EZQN7rQAC5eVkBOuX4YcP30oEexzfYprmNymbCgACr8ExG-P56UomIatnBwXG7gEAAwIAA3kAAy4E',
'🍋 🍉 🍒': 'AgACAgIAAx0EZQN7rQAC5eZkBOua048870pDyBK5XG0wEk0dvQACyMExG-P56Upws_KpHj3RZwEAAwIAA3kAAy4E',
'🍋 🍉 🍋': 'AgACAgIAAx0EZQN7rQAC5edkBOueuwGdjrxGN6AFOgxVquvqzgACvsExG-P56UqZVWg25TOCRgEAAwIAA3kAAy4E',
'🍋 🍓 🍉': 'AgACAgIAAx0EZQN7rQAC5ehkBOuhUJqB1_GL6ZUU0oC2jorGGAACsMExG-P56UpabTEGizhOQgEAAwIAA3kAAy4E',
'🍋 🍓 🍓': 'AgACAgIAAx0EZQN7rQAC5elkBOuldymm-0y7jp-q9daTUHKoDwACx8ExG-P56UpFqK6rYFcWMAEAAwIAA3kAAy4E',
'🍋 🍓 🍒': 'AgACAgIAAx0EZQN7rQAC5epkBOupLcZrUBgbT8notNmfp-hqhAACscExG-P56Ur05Obd-7s8zwEAAwIAA3kAAy4E',
'🍋 🍓 🍋': 'AgACAgIAAx0EZQN7rQAC5etkBOusTZYgBnRvOw3k5io21QoJ2AACtsExG-P56UrOmGO8HajC-AEAAwIAA3kAAy4E',
'🍋 🍒 🍉': 'AgACAgIAAx0EZQN7rQAC5exkBOuwvSWk3xK_4P0VlaMrcBouOAACDsExG8hrMUuJiLLXZ1j1JQEAAwIAA3kAAy4E',
'🍋 🍒 🍓': 'AgACAgIAAx0EZQN7rQAC5e1kBOu0EsK0dSVcfErOQ73tcvDxLgACGMExG8hrMUscdqnp2VpYSgEAAwIAA3kAAy4E',
'🍋 🍒 🍒': 'AgACAgIAAx0EZQN7rQAC5e5kBOu3GhG_-k-M0f-faM8DBYXRggACt8ExG-P56Ur88xmwiiiGewEAAwIAA3kAAy4E',
'🍋 🍒 🍋': 'AgACAgIAAx0EZQN7rQAC5e9kBOu7tTr-WUVbpaPwpZ4gsP7qXwACxMExG-P56Uo7iNLkA3eWNgEAAwIAA3kAAy4E',
'🍋 🍋 🍉': 'AgACAgIAAx0EZQN7rQAC5fBkBOu_tutMlCusBWPteJRRRpsjzgACusExG-P56UqN8yYCvOEYFwEAAwIAA3kAAy4E',
'🍋 🍋 🍓': 'AgACAgIAAx0EZQN7rQAC5fFkBOvCOydjkIBbc7QTIY7453ciswACu8ExG-P56UqudzPUdSHcbAEAAwIAA3kAAy4E',
'🍋 🍋 🍒': 'AgACAgIAAx0EZQN7rQAC5fJkBOvGGBzdgPHUX3B8y5Wh5jZNYgACy8ExG-P56UrQqJTrxuJJHQEAAwIAA3kAAy4E',
'🍋 🍋 🍋': 'AgACAgIAAx0EZQN7rQAC5fNkBOvJ3EryLc7l3qTurq9qpwTdJgACC8ExG8hrMUtL5D3BGw2LDAEAAwIAA3kAAy4E'
}

passive_skill_list = [
'<b>Нет навыка ❌</b>\n',
'<b>Крепкое здоровье 🫀 (пассив)</b>\nКвадраты восстанавливают здоровье вместо блоков\n',
'<b>Повышенная сила 🟡 (пассив)</b>\nБольше жёлтых кругов на поле, при их складывании появляется звезда\n',
'<b>Повышенная скорость 💙 (пассив)</b>\nБольше синих сердец на поле, при их складывании появляется звезда\n',
'<b>Последний шанс 💔 (пассив)</b>\nНа одну единицу урона больше если 2 хп или меньше\n',
'<b>Энергичность ⚡️ (пассив)</b>\nНа одну единицу урона больше при максимальном хп\n',
'<b>Девять жизней 🐱 (пассив)</b>\nСпасает от смерти один раз за бой\n',
'<b>Атака со спины 💫 (пассив)</b>\n4 шага на первый ход\n',
'<b>Удача ☘️ (пассив)</b>\n20% шанс увернуться от любой атаки, срабатывает не более двух раз за бой\n',
'<b>Справедливость ⚖️ (пассив)</b>\nДополнительный шаг если твоё хп меньше или равно суммарному хп врагов\n',
'<b>Неоправданный риск ♠️ (пассив)</b>\nНа одну единицу урона больше если атаковать во время последнего шага не имея при этом блоков\n'
]

active_skill_list = [
'<b>Нет навыка ❌</b>\n',
'<b>Звезда ⭐️ (актив)</b>\nПревращает выбранную фигуру в звезду\n',
'<b>Разрушение 💥 (актив)</b>\nРазрушает выбранную фигуру, заменяя её пустотой\n',
'<b>Перемешать 🔄 (актив)</b>\nПеремешывает поле, при этом количество фигур каждого цвета не изменяется\n',
'<b>Превентивный удар 🗡 (актив)</b>\nЗабирает один шаг, но наносит урон врагу\n',
'<b>Защитная стойка 🛡 (актив)</b>\nЗабирает один шаг, но даёт один блок\n',
'<b>Звёздный час 🌟 (актив)</b>\nДве случайные фигуры заменяет звёздами, не работает если на поле уже есть звёзды\n',
'<b>Ход конём 🧩 (актив)</b>\nЕсли выбранных фигур на поле не меньше одиннадцати, заменяет их на пустоту и делает действие в зависимости от типа фигуры (1 блок, 1 урон или 1 шаг)\n',
'<b>Аннигиляция 🔥 (актив)</b>\nУничтожает ряд фигур на поле\n',
'<b>Звёздная ярость ✨ (актив)</b>\nУничтожает выбранную звезду, но даёт 1 шаг\n',
'<b>Умножение 💕 (актив)</b>\nДобавляет 2 фигуры выбранного цвета на поле, не работает со звёздами\n'
]

skill_names = [
'Нет навыка ❌',
'Звезда ⭐️',
'Разрушение 💥',
'Перемешать 🔄',
'Прев удар 🗡',
'Защ стойка 🛡',
'Звзд час 🌟',
'Ход конём 🧩',
'Аннигиляция 🔥',
'Звзд ярость ✨',
'Умножение 💕'
]

nekosas = {
540255407: (16, 4),
738931917: (17, 2),
523497602: (4, 7),
729883976: (19, 2),
448214297: (29, 4),
503671007: (3, 10),
460507186: (19, 1),
783003689: (27, 1),
5417937009: (11,3)
}

enemy_list = [
{'id': 0, #АЙДИ ВРАГА
'name': '', #ИМЯ ВРАГА
'maxhp': 0, #МАКСИМАЛЬНОЕ ХП ВРАГА, 0 ДЛЯ БЕССМЕРТИЯ
'hp': 0, #ХП ВРАГА
'deathspawn': 0, #КТО ЗАСПАВНИТСЯ ПОСЛЕ СМЕРТИ ВРАГА
'deathturns': 0, #КАК ИЗМЕНЯТСЯ ХОДЫ КОГДА ВРАГ СДОХНЕТ
'dodge': False, #МОЖЕТ ЛИ ВРАГ УВЕРНУТЬСЯ
'damage': 0, #УРОН ВРАГА
'turnchange': None #КЕМ ВРАГ СТАНЕТ ВО ВРЕМЯ СВОЕГО ХОДА
},

{'id': 1,
'name': 'Gayster 💥',
'maxhp': 3,
'hp': 3,
'deathspawn': 0,
'deathturns': 0,
'dodge': False,
'damage': 1,
'turnchange': None
},

{'id': 2,
'name': 'Gayster blaster',
'maxhp': 2,
'hp': 2,
'deathspawn': 0,
'deathturns': 0,
'dodge': False,
'damage': 0,
'turnchange': 3
},

{'id': 3,
'name': 'Gayster blaster 💥💥',
'maxhp': 2,
'hp': 2,
'deathspawn': 0,
'deathturns': 0,
'dodge': False,
'damage': 2,
'turnchange': 2
},

{'id': 4,
'name': 'Петрович 💥',
'maxhp': 3,
'hp': 3,
'deathspawn': 5,
'deathturns': 1,
'dodge': False,
'damage': 1,
'turnchange': None
},

{'id': 5,
'name': 'Gay bomb 💥💥',
'maxhp': 1,
'hp': 1,
'deathspawn': 0,
'deathturns': -10,
'dodge': False,
'damage': 2,
'turnchange': 0
},

{'id': 6,
'name': 'ЛГБТ Слизень',
'maxhp': 3,
'hp': 3,
'deathspawn': 7,
'deathturns': 0,
'dodge': False,
'damage': 0,
'turnchange': None
},

{'id': 7,
'name': 'Радужная слизь 💥',
'maxhp': 1,
'hp': 1,
'deathspawn': 0,
'deathturns': 0,
'dodge': False,
'damage': 1,
'turnchange': None
},

{'id': 8,
'name': 'Рикардо Фуррилос 💥💥 🫥',
'maxhp': 1,
'hp': 1,
'deathspawn': 0,
'deathturns': 0,
'dodge': True,
'damage': 2,
'turnchange': None
},

{'id': 9,
'name': 'Рикардо Фуррилос 💥💥',
'maxhp': 1,
'hp': 1,
'deathspawn': 0,
'deathturns': 0,
'dodge': False,
'damage': 2,
'turnchange': 8
},

{'id': 10,
'name': 'Sanya 💥💥 🫥',
'maxhp': 3,
'hp': 3,
'deathspawn': 0,
'deathturns': 0,
'dodge': True,
'damage': 0,
'turnchange': None
},

{'id': 11,
'name': 'Sanya 💥💥',
'maxhp': 3,
'hp': 3,
'deathspawn': 0,
'deathturns': 0,
'dodge': False,
'damage': 0,
'turnchange': 10
},

{'id': 12,
'name': 'Pilk blaster',
'maxhp': 0,
'hp': 0,
'deathspawn': 12,
'deathturns': 0,
'dodge': False,
'damage': 0,
'turnchange': 13
},

{'id': 13,
'name': 'Pilk blaster 💥💥',
'maxhp': 0,
'hp': 0,
'deathspawn': 12,
'deathturns': 0,
'dodge': False,
'damage': 2,
'turnchange': None
}
]

item_list = [
('<b>Пусто ❌</b>','AgACAgIAAx0CZQN7rQABAWTTZMhPYtB0kuCiwATnG1etffSyRzAAAijHMRvAkkhKIBIUC0M-gQEBAAMCAANzAAMvBA'),
('<b>Jojo символы 🈵</b>','AgACAgIAAx0CZQN7rQABAWTVZMhPlyJOyDcJG2xk5pGpYhnwJxQAAinHMRvAkkhKv6wDUPCWm1cBAAMCAANzAAMvBA'),
('<b>Шапка на нг 🎄</b>','AgACAgIAAx0CZQN7rQABAWTXZMhPyDIAAYqzhCmth2SFN2KPNWZAAAIqxzEbwJJISrAUtMwQX8KFAQADAgADcwADLwQ'),
('<b>Уебанская кепка 🥴</b>','AgACAgIAAx0CZQN7rQABAWTaZMhP3GTw9G23D_Y5nzZwbc6uCX8AAivHMRvAkkhKsMjIxJRfw3EBAAMCAANzAAMvBA'),
('<b>Стопхам 🛑</b>','AgACAgIAAx0CZQN7rQABAWTcZMhQJt-k_AWKccq2u2yR6iL5OygAAizHMRvAkkhKSZAGS4qaZSwBAAMCAANzAAMvBA'),
('<b>Кiшка 😽</b>','AgACAgIAAx0CZQN7rQABAWTeZMhQRCwhvIXT1nOmEds1Ih1BWCwAAi3HMRvAkkhKAjQDctpbzYABAAMCAANzAAMvBA'),
('<b>Михуил 😈</b>','AgACAgIAAx0CZQN7rQABAWThZMhQZb8X__z1eMkcelgPl7nuZ2YAAi7HMRvAkkhKcxIOv1Vh9LgBAAMCAANzAAMvBA'),
('<b>Заебумба 👍</b>','AgACAgIAAx0CZQN7rQABAWTjZMhQi40KOLAAAYZ9j6BtzToYc0SZAAIvxzEbwJJISkt9q2G1AlYHAQADAgADcwADLwQ'),
('<b>Сойджаки 😲</b>','AgACAgIAAx0CZQN7rQABAWTlZMhQqHubHvb38_EXi2rrWfgwF68AAjDHMRvAkkhKGfXWKlsWFe0BAAMCAANzAAMvBA'),
('<b>Свег очки 😎</b>','AgACAgIAAx0CZQN7rQABAWTnZMhQxeMa94lUuvM8OfX4CLyvsJIAAjHHMRvAkkhKPsS1o3KgNaoBAAMCAANzAAMvBA'),
('<b>Флексаир ✈️</b>','AgACAgIAAx0CZQN7rQABAWTpZMhQ3ryIDQ2XA4KPEH-571n6imgAAjLHMRvAkkhKildH_O3DRQcBAAMCAANzAAMvBA'),
('<b>Косяк 🚬</b>','AgACAgIAAx0CZQN7rQABAWT1ZMhW19twM_kixEEdmT9G7yoGeCIAAjbHMRvAkkhK4SpVZnqaUGwBAAMCAANzAAMvBA'),
('<b>Коронавирусы 🦠</b>','AgACAgIAAx0CZQN7rQABAWT4ZMhXC1nUEMHzTR_TnkHDaERMFJsAAjfHMRvAkkhKcFPPd0HNPtEBAAMCAANzAAMvBA'),
('<b>Пакет на голову 🛍</b>','AgACAgIAAx0CZQN7rQABAWT6ZMhXKTejIS_TClgr4YdqAsBAR2YAAjjHMRvAkkhKJ4aSmL_DVSIBAAMCAANzAAMvBA'),
('<b>Пистолетус 🔫</b>','AgACAgIAAx0CZQN7rQABAWT8ZMhXScEDYL5cZvNJ-YxVCvbXRrsAAjnHMRvAkkhKP-XWeMXvqhkBAAMCAANzAAMvBA'),
('<b>ЧВК Некосасы 🕷</b>','AgACAgIAAx0CZQN7rQABAWT_ZMhXb6pEi1jKbAGCBYzlmKF9-4EAAjrHMRvAkkhKJfDcotJVF6MBAAMCAANzAAMvBA'),
('<b>Шапка укронациста 🇺🇦</b>','AgACAgIAAx0CZQN7rQABAWUBZMhXnuBEd5EqW6CZGKiyHGRKZU4AAjvHMRvAkkhKddahGLlQhUABAAMCAANzAAMvBA'),
('<b>Стресс 🤯</b>','AgACAgIAAx0CZQN7rQABAWUDZMhXvoRvAAEC9ntqJfCc1lYyMliNAAI8xzEbwJJISsX9Diq8sw42AQADAgADcwADLwQ'),
('<b>Мини гура 🦈</b>','AgACAgIAAx0CZQN7rQABAWUFZMhX2q5O6QEEwxlSUaM_TRalSUkAAj3HMRvAkkhKZ0rZ5Cwr32QBAAMCAANzAAMvBA'),
('<b>Лечебные травы 🪴</b>','AgACAgIAAx0CZQN7rQABAWUHZMhX99pT1YIOhtXIpKX9XwR7YIsAAj7HMRvAkkhKDemXjg9jE44BAAMCAANzAAMvBA'),
('<b>Мать ебал 🤬</b>','AgACAgIAAx0CZQN7rQABAWUJZMhYIiD06L0mEoWgXTBLHZKNjBIAAj_HMRvAkkhKvcGIuH3WTLQBAAMCAANzAAMvBA'),
('<b>SUS 🔥</b>','AgACAgIAAx0CZQN7rQABAW1wZMtifEZUnRH5Wpzi8hUcEZuRnDsAApXKMRssnlhK2c25l9AF7B8BAAMCAANzAAMvBA'),
('<b>Нашивка 🛡</b>','AgACAgIAAx0CZQN7rQABAW10ZMtitWzLgz_Abm5x-awb2LohySYAApbKMRssnlhKhbuReK4eZAsBAAMCAANzAAMvBA')
]

enemy_photos = {
'0 0 0': 'AgACAgIAAx0EZQN7rQABAU8-ZL4mv5mzNHCQD7JgsEUd1Gq2ooQAAvnJMRuFY_FJf55t1YagDosBAAMCAAN4AAMvBA',
'0 9 0': 'AgACAgIAAx0EZQN7rQABAU8_ZL4mxcf6md-k5lfcmX0qyc2i14EAAvzJMRuFY_FJdOJWTt9RuQsBAAMCAAN4AAMvBA', 
'0 8 0': 'AgACAgIAAx0EZQN7rQABAU9BZL4myoYJg5LAJpswDPBmS1gzkA8AAv3JMRuFY_FJgYCfyy2U_CEBAAMCAAN4AAMvBA', 
'0 4 0': 'AgACAgIAAx0EZQN7rQABAU9CZL4m0DSwTh9CJWA3RKWheB5mFh8AAiDKMRuFY_FJob0exPU5QyYBAAMCAAN4AAMvBA', 
'0 5 0': 'AgACAgIAAx0EZQN7rQABAU9DZL4m1phRIfeGmqaWOwzCpUS0XfwAAv_JMRuFY_FJGHnPNqeSRcUBAAMCAAN4AAMvBA', 
'0 1 2': 'AgACAgIAAx0EZQN7rQABAU9EZL4m20mlPBh7tbT1uCn_YUXa0WsAA8oxG4Vj8UlK6fWOYIaVDgEAAwIAA3gAAy8E', 
'0 1 3': 'AgACAgIAAx0EZQN7rQABAU9FZL4m4bCb8olEWAwchX7TvraR3a4AAgHKMRuFY_FJaMZt5x5A0S0BAAMCAAN4AAMvBA', 
'0 1 0': 'AgACAgIAAx0EZQN7rQABAU9GZL4m51iG79tdV5NTDLHL_Igu0qwAAgLKMRuFY_FJIJnp2k_d4D8BAAMCAAN4AAMvBA', 
'0 0 2': 'AgACAgIAAx0EZQN7rQABAU9HZL4m7FIcI29TbeBU71yb_GDJ1REAAgPKMRuFY_FJCsuCYD5KNg8BAAMCAAN4AAMvBA', 
'0 0 3': 'AgACAgIAAx0EZQN7rQABAU9IZL4m8s7HVr9xsmMAAdC1TMAYY7DjAAIEyjEbhWPxSXE7QX2XbiClAQADAgADeAADLwQ', 
'0 0 7': 'AgACAgIAAx0EZQN7rQABAU9JZL4m-OmsyCCMXq6i8ny81npDQu8AAgXKMRuFY_FJvqYN2tQBhGYBAAMCAAN4AAMvBA', 
'0 6 0': 'AgACAgIAAx0EZQN7rQABAU9KZL4m_l9HAQUeGYyY_m2M-P1EKEMAAgbKMRuFY_FJBL-5whVYaoABAAMCAAN4AAMvBA', 
'0 6 7': 'AgACAgIAAx0EZQN7rQABAU9LZL4nA2gjimgpvNUUwAMQk3KNysAAAgfKMRuFY_FJ4qfL5jqdzLYBAAMCAAN4AAMvBA', 
'0 7 0': 'AgACAgIAAx0EZQN7rQABAU9MZL4nCX0oCROMVg-spGT2e96oYNUAAgnKMRuFY_FJecay9W8w9Z8BAAMCAAN4AAMvBA', 
'0 7 7': 'AgACAgIAAx0EZQN7rQABAU9NZL4nD0JegBL4HOY7wMzmx9C8uWgAAgrKMRuFY_FJ2vHdUWmioXQBAAMCAAN4AAMvBA', 
'7 0 0': 'AgACAgIAAx0EZQN7rQABAU9OZL4nFNuncbQ9sO6H7_YS2Hwj4XIAAgvKMRuFY_FJjdyI9TBNc4oBAAMCAAN4AAMvBA', 
'7 0 7': 'AgACAgIAAx0EZQN7rQABAU9PZL4nGifFNCqEwMSkhFS-sOqxtsQAAgzKMRuFY_FJLlC1YvPqiUYBAAMCAAN4AAMvBA', 
'7 6 0': 'AgACAgIAAx0EZQN7rQABAU9QZL4nH9UAAUVKHAcMa4d-dPwSMH4pAAINyjEbhWPxSYE2naBJlPcmAQADAgADeAADLwQ', 
'7 6 7': 'AgACAgIAAx0EZQN7rQABAU9RZL4nJpt8xmWH7urYMf2sh6A9kvYAAg7KMRuFY_FJQd2pSJTDV4oBAAMCAAN4AAMvBA', 
'7 7 0': 'AgACAgIAAx0EZQN7rQABAU9SZL4nLRXaLgdbvNBN2HHQvO3jVI8AAg_KMRuFY_FJUKmXVSc12kABAAMCAAN4AAMvBA', 
'7 7 7': 'AgACAgIAAx0EZQN7rQABAU9TZL4nMybJsqbqX895JsG9VaMxUXMAAhDKMRuFY_FJs4jqxA-8YEcBAAMCAAN4AAMvBA'
}

boss_photos = {
'0 0 0': 'AgACAgIAAx0EZQN7rQABAdiCZQABFpPO7FV7PNZd_UlhSQkClG00AAKs0jEbmoTRS2FqTQjDX_FaAQADAgADeAADMAQ',
'0 0 12': 'AgACAgIAAx0EZQN7rQABAdiDZQABFphDzq0tL70uCgvH41mX4iodAAKgyTEb5toBSKVoW_G2Gt0iAQADAgADeAADMAQ',
'0 0 13': 'AgACAgIAAx0EZQN7rQABAdiEZQABFp7Bv9cV6_2W4IXaysRooguEAAKhyTEb5toBSMbYHan7SjkBAQADAgADeAADMAQ',
'0 10 0': 'AgACAgIAAx0EZQN7rQABAdiFZQABFqTsRAfkMK8jfItA398Dv67aAAK9yTEb5toBSNl-z2fVqzOvAQADAgADeAADMAQ',
'0 10 12': 'AgACAgIAAx0EZQN7rQABAdiGZQABFql5Mpt1FV2lVndjUrIKOlQ_AAK-yTEb5toBSEOHX-Nn8hSQAQADAgADeAADMAQ',
'0 10 13': 'AgACAgIAAx0EZQN7rQABAdiHZQABFq-mVASgZt14NFXYQ8wn-fAjAAK_yTEb5toBSPdy8m2HuX4dAQADAgADeAADMAQ',
'0 11 0': 'AgACAgIAAx0EZQN7rQABAdiIZQABFrUTIEzC5NGQHxPrXQfjnRirAALAyTEb5toBSPIYBVYXWgdMAQADAgADeAADMAQ',
'0 11 12': 'AgACAgIAAx0EZQN7rQABAdiJZQABFrqNo4nfCOYNKlXcLR4-U-ypAALByTEb5toBSB2tQ8_f9I-DAQADAgADeAADMAQ',
'0 11 13': 'AgACAgIAAx0EZQN7rQABAdiKZQABFsD7nKTd0QHPTR3jQ9r0Kd0hAALCyTEb5toBSBHusU0i-pdxAQADAgADeAADMAQ',
'12 0 0': 'AgACAgIAAx0EZQN7rQABAdiLZQABFsVN5bKW7JxJBwkClna1V8gAA6bJMRvm2gFI4qtXr-aQB70BAAMCAAN4AAMwBA',
'12 0 12': 'AgACAgIAAx0EZQN7rQABAdiMZQABFsss4HL4pveMcduDL9BNmDdiAAKnyTEb5toBSLeym1l4VGEGAQADAgADeAADMAQ',
'12 0 13': 'AgACAgIAAx0EZQN7rQABAdiNZQABFtHQT3u6BbN7Mofmp43x5PSyAAKoyTEb5toBSNnOjM3VzqBrAQADAgADeAADMAQ',
'12 10 0': 'AgACAgIAAx0EZQN7rQABAdiOZQABFtbjhhCquZDnuaFn8Fj4RR0SAALEyTEb5toBSLhbeywx9Lk5AQADAgADeAADMAQ',
'12 10 12': 'AgACAgIAAx0EZQN7rQABAdiRZQABFtwSkzhSk38m78fVi1kg3NDpAALGyTEb5toBSBM5CSE2MUZmAQADAgADeAADMAQ',
'12 10 13': 'AgACAgIAAx0EZQN7rQABAdiTZQABFuII9tX8F0cl2tBDTyDuIo-cAALIyTEb5toBSFxfNacJWS6CAQADAgADeAADMAQ',
'12 11 0': 'AgACAgIAAx0EZQN7rQABAdiVZQABFucq49rncFXUyBQj5ecKGnIlAALKyTEb5toBSN6JGXPGmRJUAQADAgADeAADMAQ',
'12 11 12': 'AgACAgIAAx0EZQN7rQABAdiWZQABFu3QDOc7hJSoFEAFB44_mWXpAALLyTEb5toBSLLLd4f9kKO4AQADAgADeAADMAQ',
'12 11 13': 'AgACAgIAAx0EZQN7rQABAdiYZQABFvIJulTRAxIch78AAY6LWCZbTAACzckxG-baAUieSXs1dsfFDgEAAwIAA3gAAzAE',
'13 0 0': 'AgACAgIAAx0EZQN7rQABAdiaZQABFvi2yg8NIZJZxpwnAAGXoWGo6gACsMkxG-baAUhSN4-NVpKuuwEAAwIAA3gAAzAE',
'13 0 12': 'AgACAgIAAx0EZQN7rQABAdicZQABFv3rvhKeUbzIP5yCXDti2kvVAAKyyTEb5toBSP1_yGm_2dfTAQADAgADeAADMAQ',
'13 0 13': 'AgACAgIAAx0EZQN7rQABAdieZQABFwPpEwrfF8GzAAGIZosPXtwaxQACs8kxG-baAUjFBX42m8YDeAEAAwIAA3gAAzAE',
'13 10 0': 'AgACAgIAAx0EZQN7rQABAdigZQABFwrDzZdIY8SI0Yc4GiMLXgFlAALTyTEb5toBSB7oZVf4FZzAAQADAgADeAADMAQ',
'13 10 12': 'AgACAgIAAx0EZQN7rQABAdiiZQABFxB1R92LCLPonMKW1CMWI7DIAALVyTEb5toBSI-1KMD8NMVxAQADAgADeAADMAQ',
'13 10 13': 'AgACAgIAAx0EZQN7rQABAdikZQABFxYXqFo6LxEVBOEs1X_xpGQUAALXyTEb5toBSPtbHJaKSoEZAQADAgADeAADMAQ',
'13 11 0': 'AgACAgIAAx0EZQN7rQABAdimZQABFxxVZLubMrd1LPi-hVL8LrlRAALYyTEb5toBSGjHkaMnG5fKAQADAgADeAADMAQ',
'13 11 12': 'AgACAgIAAx0EZQN7rQABAdinZQABFyGG1X2KoMKOpnbHufrfuU2nAALZyTEb5toBSO8lBvXdo8XmAQADAgADeAADMAQ',
'13 11 13': 'AgACAgIAAx0EZQN7rQABAdioZQABFycxZ7L3FE2yrNmdQ6CqbuU3AALayTEb5toBSGJFI--M3b6PAQADAgADeAADMAQ'
}

prof = [
'Монтажник',
'Электрик',
'Токарь',
'Сварщик',
'Охранник'
]

cmd_noarg = ['неко','вещи','навыки','топ','топ деньги','погладить','покормить','выгулять',
'кладбище','отдать','драться','показать','откупиться','завод','выгнать дебилов','вернуть дебилов','некобаза',
'улучшить','уйти','купить','открыть','вискас','монстр','адреналин','gender changer','коробка','назад',
'гараж','купить машину','арена','лицензия','продлить','войти','портал','данж','босс','казино',
'пуск','слоты','покер','покрасить машину','дизайн','покрасить базу','верстак','починить','гардероб',
'приложить','повтор','руководство','сразиться','атаковать','съебать','гайд бои','гайд данж','гайд босс']

cmd_arg = ['имя','донат','бой','фото','использовать','!set','создать','разобрать']

cmd_allowed_bolnitsa = ['неко','вещи','навыки','топ','топ деньги','некобаза','гараж',
'кладбище','казино','арена','лицензия','портал','данж','босс','использовать антипохмелин', 'руководство','гайд бои','гайд данж','гайд босс']

cmd_allowed_gulat = ['неко','вещи','навыки','топ','топ деньги','некобаза','гараж',
'кладбище','казино','арена','портал','данж','босс','отдать','драться','показать','откупиться',
'уйти','купить','открыть','вискас','монстр','адреналин','gender changer','коробка','назад',
'приложить','повтор', 'руководство','атаковать','съебать','гайд бои','гайд данж','гайд босс']

cmd_photo = ['покрасить машину','дизайн','покрасить базу']

blocked_cmd = {
	0: ['завод','улучшить','некобаза','гараж','лицензия','продлить'],
	1: ['лицензия','продлить'],
	2: []
}

help_text = [
'''
<b>Раздел: Основное</b>

<i><u>Неко</u></i> – основная информация про твою некодевочку и её потребности
<i><u>Топ</u></i> – самые пиздатые некочаны
<i><u>Топ деньги</u></i> – самые богатые некочаны
<i><u>Кладбище</u></i> – сдохшие некочаны
<i><u>Некобаза</u></i> – твоя хата, улучшай её чтобы открыть верстак и другие штуки
<i><u>Гараж</u></i> – здесь можно купить тачку для поездки в данж или к боссу
<i><u>Лицензия</u></i> – важный документ, не забывай её продлевать, иначе плохо кончишь во время прогулки
''',
'''
<b>Раздел: Кошкожена</b>

<i><u>Покормить</u></i> – корми свою хуйню раз в 6 часов чтобы повышать доверие
<i><u>Выгулять</u></i> – выгуливай свою хуйню раз в 8 часов и находи приключения на жопу
<i><u>Погладить</u></i> – гладь свою хуйню чтобы поднять настроение. Благодаря этому она будет быстрее отдыхать, чаще хотеть есть и гулять
<i><u>Имя [текст]</u></i> – дай своей кошкожене имя от которого она охуеет
<i><u>Гардероб</u></i> – когда-нибудь ты найдешь хайповые украшения и сможешь одеть их здесь
<i><u>Навыки</u></i> – боевые умения твоей некодевочки, используй адреналин чтобы раскрыть её потенциал
''',
'''
<b>Раздел: Активности</b>

<i><u>Завод</u></i> – каждый день трудись на благо Некославии
<i><u>Казино</u></i> – проеби всё что заработал на слотах или в покере
<i><u>Арена</u></i> – отпизди чужих некочанов и забери их кеш. От 30-ти доверия
<i><u>Данж</u></i> – загадочный портал в лгбт мир, полный опасностей и лута. От 60-ти доверия
<i><u>Босс</u></i> – собери лучшую тиму и сразись с ебакой. От 120-ти доверия
''',
'''
<b>Раздел: Инвентарь</b>

<i><u>Вещи</u></i> – твой инвентарь
<i><u>Использовать [назв]</u></i> – юзнуть предмет, эффект зависит от предмета. Учти, что кости и вискас используются автоматически, данная команда отключает это
<i><u>Донат [назв] [колво]</u></i> – передать указанное количество указанного предмета ответом на сообщение получателя
'''
]

guide_text = [
'''
Это ультимативный гайд по уебанской боевой системе, вдохновлённой игрой The Legend of Bumbo. В основе лежит складывание фигур по 4 в ряд
			
<b>Элементы интерфейса (см рисунок):</b>
1️⃣  Информация про хп твоего некочана, хп вражины и оставшиеся шаги. Главная цель – захуярить врага и не сдохнуть самому. Шаги тратятся на передвижение фигур, когда шаги заканчиваются ход переходит к мобам или другим игрокам. Для мобов действуют обозначения:
💥 – кол-во урона, которое моб нанесёт во время своего хода
🫥 – единоразовый уворот от любой твоей атаки
2️⃣  Кнопки для выбора цели, которая будет получать урон
3️⃣  Игровое поле, на котором нужно складывать одинаковые фигуры по 4 в ряд. Эффекты фигур:
🟥 🟧 – блок
🟡 🟢 – атака
💙 – дополнительные шаги
⭐️ – участвует в комбинациях вместо любой другой фигуры
🦴 – без эффекта, тупо засоряет поле
Также возможно сложить 5 или 6 фигур чтобы, например, нанести больше урона или получить больше шагов
4️⃣  Кнопки активных навыков. Каждый такой навык можно использовать раз за ход, пассивные же навыки действуют всегда

<b>Как увеличить боевую мощь твоей некодевочки?</b>
<b>●</b> Спаивай её адреналином и открывай навыки
<b>●</b> Крафти шмот на верстаке для повышения максимального хп
<b>●</b> Кости санса полезны в пвп
<a href="https://i.imgur.com/gcovarT.png">᠌᠌</a>
''',
'''
Это ультимативный гайд по прохождению уебанского данжа. Суть в том чтобы собрать максимум лута и съебать с ним

<b>Элементы интерфейса (см рисунок):</b>
1️⃣  Количество собранного лута
2️⃣  Карта данжа. Имеет такие обозначения:
🟢 – твоё местоположение
🟥 – неисследованная комната
🟩 – пустая исследованная комната
🟧 – исследованная комната, но в ней осталось действие
Чем больше клеток исследуешь, тем больше соберёшь ништяков. Также старайся избегать боёв с мобами
3️⃣  Кнопки перемещения по карте и кнопка выхода. Данж завершается двумя способами – смертью некодевочки или этой кнопкой. В первом случае весь собранный лут проёбывается
<a href="https://i.imgur.com/GpnY2AL.png">᠌᠌</a>
''',
'''
Это ультимативный гайд по уебанской битве с боссом. Она похожа на бой в данже, но имеет <b>важные особенности:</b>

<b>●</b> Перед боем есть возможность закупиться полезными предметами. Они одноразовые и используются по одному за ход
<b>●</b> Враги ходят после того как походят все игроки, вражеский урон проходит по всем игрокам одновременно
<b>●</b> Pilk blaster бессмертный, но пропускает ход если его атаковать
<b>●</b> Sanya, если пробивает броню, накладывает один из двух эффектов. Первый это яд, который наносит один урон каждый вражеский ход и может быть убран только специальным предметом. Второй эффект представляет собой спавн нескольких костей на поле
'''
]
cmd_events = {
	'отдать': (1,),
	'драться': (1,),
	'показать': (7,),
	'откупиться': (7,),
	'приложить': (11,),
	'уйти': (2,3,8,11),
	'купить': (4,5,6,9,10),
	'открыть': (2,),
	'вискас': (3,),
	'монстр': (3,),
	'коробка': (3,),
	'адреналин': (8,),
	'gender changer': (8,),
	'атаковать': (12,),
	'cъебать': (12,),
	'назад': (4,5,6,9,10)
}

struct_dungeon = {
	'type': 'dungeon',
	'map': [],
	'message': 0,
	'chat': 0,
	'wait': 0,
	'generation': [],
	'co': 0,
	'wh': 0,
	'mo': 0,
	'he': 0,
	'field': [],
	'selected': -1,
	'cur_x': 0,
	'cur_y': 0,
	'hp': 4,
	'maxhp': 4,
	'name': 'Некодевочка',
	'gender': 0,
	'skills': [],
	'temp_skills': [],
	'enemies': []
}

struct_papers = {
	'type': 'papers',
	'images': [],
	'wait': 0,
	'chat': 0,
	'message': 0,
	'stage': 0,
	'mistakes': 0,
	'today_text': ''
}

struct_poker = {
    'type': 'poker',
    'cards': [],
    'event': -1,   
    'wait': 0,  
    'chat': 0, 
    'message': 0,
    'hand': [],
    'players': [],
    'bank': [],
    'names': [],
    'money': [],
    'dead': [],
    'vabank': [],
    'minbet': 0
}

struct_boss = {
	'type': 'boss',
	'players': [],
    'zakup': [],
    'event': 0,
    'wait': 0,
    'chat': 0,
    'message': 0,
    'all_hp': [],
    'all_maxhp': [],
    'enemies': [],
    'all_poisoned': [False,False,False],
    'all_blocks': [0,0,0],
    'all_field': [],
    'selected': -1,
    'all_name': [],
    'all_skills': []
}

struct_battle = {
	'type': 'battle',
	'players': [],
	'one': 0,
	'two': 0,
    'event': 0,
    'wait': 0,
    'cost': 0,
    'chat': 0,
    'message': 0,
    'fieldone': [],
    'fieldtwo': [],
    'selected': -1,
    'nameone': 'Некодевочка',
    'nametwo':  'Некодевочка',
    'imageone': '',
    'imagetwo': '',
    'skillone': [],
    'skilltwo': [],
    'bone_one': 0,
    'bone_two': 0,
    'starter': 1
}

BATTLE_TIMEOUT = 1*3600
DUNGEON_TIMEOUT = 24*3600
BOSS_TIMEOUT = 24*3600
LICENSION_TIMEOUT = 5*24*3600
GULAT_TIMEOUT = 8*3600
KORMIT_TIMEOUT = 6*3600
DESIGN_TIMEOUT = 1*3600
TIMESTAMP = 2*3600
REPORT_TIMEOUT = 24*3600
HAPPY_TIMEOUT = [-5400,-2700,0,2700,5400]
DELETE_MINUTES = 10

REP_ARENA = 30
REP_DUNGEON = 60
REP_BOSS = 120

TOKEN = os.environ['TOKEN']
APP_URL = os.environ['APP_URL']
USERNAME = os.environ['USERNAME']
PASSWORD = os.environ['PASSWORD']

SERVICE_CHATID = -1001694727085
NEKOSLAVIA_CHATID = -1001268892138
ME_CHATID = 738931917

#AgACAgIAAx0CZQN7rQACyrNjGc35xHSmb1gR4r9IgIkFXObqRgAC5r0xG0V90EgpsZ5EAAGzE7UBAAMCAANzAAMpBA КАЗИНО
#AgACAgIAAx0CZQN7rQACrPNi2TTbjCTpB2sEekm_cYy69euvVgACYr8xG35hyUq6nUwvpV7fGgEAAwIAA3MAAykE РИКАРДО
#AgACAgIAAx0CZQN7rQABAbyyZPJog2CKZ3ieJzCezJ8xm46CsaUAAvfSMRsLo5FLxnwb0GGJgJgBAAMCAANzAAMwBA ЛАРЕК

# elif cmd == 'отпиздить':
# 			if car == 0:
# 				bot.send_message(message.chat.id, 'Лох у тебя нет некомобиля')
# 				bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAEFLW9iwHwLLVxr-1f5AAG6VRQQwGfiJ1kAAjoSAAIiZ1hI6TCE3lJaV4EpBA')
# 				return
# 			if inventory['monster'] < 1:
# 				bot.send_message(message.chat.id, 'Сначала заправь некомобиль дегенерат')
# 				bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAEFLW9iwHwLLVxr-1f5AAG6VRQQwGfiJ1kAAjoSAAIiZ1hI6TCE3lJaV4EpBA')
# 				return
# 			if message.reply_to_message is None:
# 				bot.send_message(message.chat.id, 'Я же сказал ответом на сообщение даун')
# 				bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAEFLW9iwHwLLVxr-1f5AAG6VRQQwGfiJ1kAAjoSAAIiZ1hI6TCE3lJaV4EpBA')
# 				return
# 			idk = message.reply_to_message.from_user.id
# 			if idk == message.from_user.id:
# 				bot.send_message(message.chat.id, 'Вот сам себя и пизди, а мне больше не пиши')
# 				bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAEFLW9iwHwLLVxr-1f5AAG6VRQQwGfiJ1kAAjoSAAIiZ1hI6TCE3lJaV4EpBA')
# 				return
# 			data = cursor.execute(f'SELECT bolnitsa,chel FROM neko WHERE id = '+str(idk))
# 			data = data.fetchone()
# 			if data is None:
# 				bot.send_message(message.chat.id,'У этого лоха нет некодевочки')
# 				bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAEFLW9iwHwLLVxr-1f5AAG6VRQQwGfiJ1kAAjoSAAIiZ1hI6TCE3lJaV4EpBA')
# 				return
# 			b = int(data[0] - time.time())
# 			chel = str(data[1]).rstrip()
# 			if b > 0:
# 				bot.send_message(message.chat.id,'Этот лох уже в больнице')
# 				bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAEFLW9iwHwLLVxr-1f5AAG6VRQQwGfiJ1kAAjoSAAIiZ1hI6TCE3lJaV4EpBA')
# 				return
# 			biba = random.randint(21600,36000)
# 			b = int(time.time()+biba)
# 			biba = math.ceil(biba/3600)
# 			txt = 'Прохожие видели, как кого-то силой затолкали в розовую буханку без номеров и увезли в неизвестном направлении. Обходясь без подробностей, <a href="tg://user?id='+str(idk)+'">'+str(chel)+'</a> отправился в больницу на ' + str(biba) + ' часов 💊'
# 			bot.send_message(message.chat.id,txt,parse_mode='HTML')
# 			bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAEGKY5jU0Mm9xVPCdaaFU7LHYBXnA4o3gACyiQAAp0NSEv_PF-UBc--kioE')
# 			inventory['monster'] -= 1
# 			cursor.execute(f"UPDATE neko SET inventory = '{pack(inventory)}' WHERE id = {message.from_user.id}")
# 			cursor.execute(f'UPDATE neko SET bolnitsa = {b} WHERE id = {idk}')

# elif cmd == 'спасти':
# 			if car == 0:
# 				bot.send_message(message.chat.id, 'Лох у тебя нет некомобиля')
# 				bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAEFLW9iwHwLLVxr-1f5AAG6VRQQwGfiJ1kAAjoSAAIiZ1hI6TCE3lJaV4EpBA')
# 				return
# 			if inventory['monster'] < 1:
# 				bot.send_message(message.chat.id, 'Сначала заправь некомобиль дегенерат')
# 				bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAEFLW9iwHwLLVxr-1f5AAG6VRQQwGfiJ1kAAjoSAAIiZ1hI6TCE3lJaV4EpBA')
# 				return
# 			if message.reply_to_message is None:
# 				bot.send_message(message.chat.id, 'Я же сказал ответом на сообщение даун')
# 				bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAEFLW9iwHwLLVxr-1f5AAG6VRQQwGfiJ1kAAjoSAAIiZ1hI6TCE3lJaV4EpBA')
# 				return
# 			idk = message.reply_to_message.from_user.id
# 			if idk == message.from_user.id:
# 				bot.send_message(message.chat.id, 'Ты сам себе ответил ебан')
# 				bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAEFLW9iwHwLLVxr-1f5AAG6VRQQwGfiJ1kAAjoSAAIiZ1hI6TCE3lJaV4EpBA')
# 				return
# 			data = cursor.execute(f'SELECT kormit,chel,name,gender FROM neko WHERE id = {idk}')
# 			data = data.fetchone()
# 			if data is None:
# 				bot.send_message(message.chat.id,'У этого лоха нет некодевочки')
# 				bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAEFLW9iwHwLLVxr-1f5AAG6VRQQwGfiJ1kAAjoSAAIiZ1hI6TCE3lJaV4EpBA')
# 				return
# 			k2 = int(data[0] - time.time())
# 			chel = str(data[1]).rstrip()
# 			n2 = str(data[2]).rstrip()
# 			gender = data[3]
# 			if k2 > -4*24*3600:
# 				text = 'Его некодевочка пока не настолько голодна'
# 				if gender == 1:
# 					text = 'Его некомальчик пока не настолько голоден'
# 				bot.send_message(message.chat.id,text)
# 				bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAEFLW9iwHwLLVxr-1f5AAG6VRQQwGfiJ1kAAjoSAAIiZ1hI6TCE3lJaV4EpBA')
# 				return
# 			text = n2 + ', конечно, испугалась тебя, но от еды не отказалась. Можешь не сомневаться, ты сделал действительно доброе дело. <a href="tg://user?id='+str(idk)+'">'+str(chel)+'</a>, тебе должно быть стыдно'
# 			if gender == 1:
# 				text = n2 + ', конечно, испугался тебя, но от еды не отказался. Можешь не сомневаться, ты сделал действительно доброе дело. <a href="tg://user?id='+str(idk)+'">'+str(chel)+'</a>, тебе должно быть стыдно'
# 			bot.send_message(message.chat.id,text,parse_mode='HTML')
# 			bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAEFVF5i2QceOMOx4OUJLMf60d1yFdEnHgACChIAAoCLWUi4Fv-mtr7ecikE')
# 			inventory['monster'] -= 1
# 			k2 = int(time.time() + KORMIT_TIMEOUT)
# 			cursor.execute(f"UPDATE neko SET inventory = '{pack(inventory)}' WHERE id = {message.from_user.id}")
# 			cursor.execute(f'UPDATE neko SET notifed = 0, kormit = {k2} WHERE id = {idk}')

#  elif box > 0:
# 			   #  boxes = boxes + box
# 			   # reward = reward + box
# 			   #cursor.execute(f"UPDATE neko SET reward = "+ str(reward) +" WHERE id = "+str(message.from_user.id))
# 			   #     cursor.execute(f"UPDATE neko SET boxes = "+ str(boxes) +" WHERE id = "+str(message.from_user.id))
# 			   #    keyboard = types.InlineKeyboardMarkup()
# 			   #   callback_button1 = types.InlineKeyboardButton(text = 'Читать 👀',callback_data = 'letter ' + str(message.from_user.id))
# 			   #  keyboard.add(callback_button1)
# 			   # callback_button2 = types.InlineKeyboardButton(text = 'Не читать ❌',callback_data = 'dont ' + str(message.from_user.id))
# 			   # keyboard.add(callback_button2)
# 			   # txt = 'Перебирая почту, ты заметил письмо, выделяющееся среди кучи бесполезных счетов и повесток. Прочитать его?'
# 			   # bot.send_photo(message.chat.id, photo = 'AgACAgIAAx0CZQN7rQAC1PhjVwdShxawIYgm_OAkJPMXuOBWiQAClsgxG1hTuEqsn8YQrmq_egEAAwIAA3MAAyoE',caption = txt,reply_markup=keyboard)
# 			   # txt = 'К тому же, у тебя под входной дверью лежала подозрительная коробка 📦. Ты предложил её просто выкинуть, но ' + nam + ', ожидаемо, не согласилась с таким решением\n\nПосылка 📦 добавлена в инвентарь\n\n<code>Донат посылка [N]</code> - передать посылку, ответом на сообщение\n\n<code>Открыть посылку</code> - открыть загадочную посылку\n'
# 			   # if gender == 1:
# 			   #     txt = 'К тому же, у тебя под входной дверью лежала подозрительная коробка 📦. Ты предложил её просто выкинуть, но ' + nam + ', ожидаемо, не согласился с таким решением\n\nПосылка 📦 добавлена в инвентарь\n\n<code>Донат посылка [N]</code> - передать посылку, ответом на сообщение\n\n<code>Открыть посылку</code> - открыть загадочную посылку\n'
# 			   # bot.send_message(message.chat.id, txt,parse_mode='HTML')

# def equ(a):
# 	if -1 in a:
# 		return False
# 	for i in range(5):
# 		b = a.copy()
# 		for j in range(len(b)):
# 			if b[j] == 5:
# 				b[j] = i
# 		if b.count(b[0]) == len(b):
# 			return True
# 	return False
	
# def fielder(field,skills,do_stars):
# 	atack = 0
# 	blocks = 0
# 	turns = 0
# 	stars = 0
# 	hp = 0
# 	b = [0,1,2,3,4]
# 	if 2 in skills:
# 		b.append(2)
# 	if 3 in skills:
# 		b.append(4)
# 	while True:
# 		found = False
# 		for j in range(6):
# 			i = 0
# 			a = [field[j*6+i],field[j*6+i+1],field[j*6+i+2],field[j*6+i+3],field[j*6+i+4],field[j*6+i+5]]
# 			if equ(a):

# 				if 2 in a and 2 in skills:
# 					stars += 1
# 				if 4 in a and 3 in skills:
# 					stars += 1

# 				if 0 in a or 1 in a:
# 					blocks = blocks + 3
# 				elif 2 in a or 3 in a:
# 					atack = atack + 3
# 				elif 4 in a:
# 					turns = turns + 3
# 				field[j*6+i] = -1
# 				field[j*6+i+1] = -1
# 				field[j*6+i+2] = -1
# 				field[j*6+i+3] = -1
# 				field[j*6+i+4] = -1
# 				field[j*6+i+5] = -1
# 				found = True
# 		for i in range(6):
# 			j = 0
# 			a = [field[j*6+i],field[(j+1)*6+i],field[(j+2)*6+i],field[(j+3)*6+i],field[(j+4)*6+i],field[(j+5)*6+i]]
# 			if equ(a):

# 				if 2 in a and 2 in skills:
# 					stars += 1
# 				if 4 in a and 3 in skills:
# 					stars += 1

# 				if 0 in a or 1 in a:
# 					blocks = blocks + 3
# 				elif 2 in a or 3 in a:
# 					atack = atack + 3
# 				elif 4 in a:
# 					turns = turns + 3
# 				field[j*6+i] = -1
# 				field[(j+1)*6+i] = -1
# 				field[(j+2)*6+i] = -1
# 				field[(j+3)*6+i] = -1
# 				field[(j+4)*6+i] = -1
# 				field[(j+5)*6+i] = -1
# 				found = True
# 		for j in range(6):
# 			for i in range(2):
# 				a = [field[j*6+i],field[j*6+i+1],field[j*6+i+2],field[j*6+i+3],field[j*6+i+4]]
# 				if equ(a):

# 					if 2 in a and 2 in skills:
# 						stars += 1
# 					if 4 in a and 3 in skills:
# 						stars += 1

# 					if 0 in a or 1 in a:
# 						blocks = blocks + 2
# 					elif 2 in a or 3 in a:
# 						atack = atack + 2
# 					elif 4 in a:
# 						turns = turns + 2
# 					field[j*6+i] = -1
# 					field[j*6+i+1] = -1
# 					field[j*6+i+2] = -1
# 					field[j*6+i+3] = -1
# 					field[j*6+i+4] = -1
# 					found = True
# 		for j in range(2):
# 			for i in range(6):
# 				a = [field[j*6+i],field[(j+1)*6+i],field[(j+2)*6+i],field[(j+3)*6+i],field[(j+4)*6+i]]
# 				if equ(a):

# 					if 2 in a and 2 in skills:
# 						stars += 1
# 					if 4 in a and 3 in skills:
# 						stars += 1

# 					if 0 in a or 1 in a:
# 						blocks = blocks + 2
# 					elif 2 in a or 3 in a:
# 						atack = atack + 2
# 					elif 4 in a:
# 						turns = turns + 2
# 					field[j*6+i] = -1
# 					field[(j+1)*6+i] = -1
# 					field[(j+2)*6+i] = -1
# 					field[(j+3)*6+i] = -1
# 					field[(j+4)*6+i] = -1
# 					found = True
# 		for j in range(6):
# 			for i in range(3):
# 				a = [field[j*6+i],field[j*6+i+1],field[j*6+i+2],field[j*6+i+3]]
# 				if equ(a):

# 					if 2 in a and 2 in skills:
# 						stars += 1
# 					if 4 in a and 3 in skills:
# 						stars += 1

# 					if 0 in a or 1 in a:
# 						blocks = blocks + 1
# 					elif 2 in a or 3 in a:
# 						atack = atack + 1
# 					elif 4 in a:
# 						turns = turns + 1
# 					field[j*6+i] = -1
# 					field[j*6+i+1] = -1
# 					field[j*6+i+2] = -1
# 					field[j*6+i+3] = -1
# 					found = True
# 		for j in range(3):
# 			for i in range(6):
# 				a = [field[j*6+i],field[(j+1)*6+i],field[(j+2)*6+i],field[(j+3)*6+i]]
# 				if equ(a):

# 					if 2 in a and 2 in skills:
# 						stars += 1
# 					if 4 in a and 3 in skills:
# 						stars += 1

# 					if 0 in a or 1 in a:
# 						blocks = blocks + 1
# 					elif 2 in a or 3 in a:
# 						atack = atack + 1
# 					elif 4 in a:
# 						turns = turns + 1
# 					field[j*6+i] = -1
# 					field[(j+1)*6+i] = -1
# 					field[(j+2)*6+i] = -1
# 					field[(j+3)*6+i] = -1
# 					found = True
# 		if -1 in field and found == False:
# 			found = True
# 		if found == False:
# 			break
# 		while True:
# 			for i in range(36):
# 				if field[i] == -1:
# 					if i < 6:
# 						if stars > 0 and do_stars:
# 							stars -= 1
# 							field[i] = 5
# 						else:
# 							field[i] = random.choice(b)
# 					else:
# 						field[i] = field[i-6]
# 						field[i-6] = -1
# 			if -1 not in field:
# 				break
				
# 	if 1 in skills:
# 		hp += blocks
# 		blocks = 0
# 	result = [atack,blocks,turns,hp]
# 	return result
# import requests
# from bs4 import BeautifulSoup
# dat = {
# 	    "target": (None,1),
# 		"MAX_FILE_SIZE": (None,1073741824),
# 		"image[]": ('neko.png',open("neko.png", "rb")),
# 		"speed": (None,"ufast"),
# 		"bg_color": (None,"000000"),
# 		"direction": (None,"right")
# }
# with requests.Session() as s:
# 	    p = s.post("https://en.bloggif.com/cube-3d?id=a034162a95c72191aaaaa92993480bde", files=dat)
# 	    print(p)
# 	    soup = BeautifulSoup(p.text, 'lxml')
# 	    tag = soup.find('a', class_='button gray-button')
# 	    print('https://en.bloggif.com' + tag['href'])

	    # with open("aboba1.html", "w", encoding="utf-8") as file:
	    # 	file.write(p.text)
	    # with open("aboba2.html", "w", encoding="utf-8") as file:
	    # 	file.write(str(p.content))


# dat = {
# 	    "target": (None,1),
# 		"MAX_FILE_SIZE": (None,1073741824),
# 		"image[]": ('neko2.png',open("neko2.png", "rb")),
# 		"type": (None,"soft")
# }
# with requests.Session() as s:
# 	    p = s.post("https://en.bloggif.com/pop-art?id=e853c1d69afdfc00b480733f5aacc884", files=dat)
# 	    print(p)
# 	    with open("aboba1.html", "w", encoding="utf-8") as file:
# 	    	file.write(p.text)
# 	    with open("aboba2.html", "w", encoding="utf-8") as file:
# 	    	file.write(str(p.content))

